### ISSUE TITLE
Crashing issue with Engrampa

### ISSUE THREAD

**Issue by ToApolytoXaos** [mate-desktop/mate-desktop#107]
My issue is rather peculiar. Even though I use MATE exclusively, last week Debian jessie 64-bit (testing) did not offer all necessary packages and I had to temporary switch to XFCE 4.10 until the dependencies were met. My menu would endlessly switch between debian's style with MATE's green default style; it made me dizzy.

Last night, while was under XFCE 4.10 I was extracting an archive with engrampa which was rather large, I decided to cancel it. As soon as I pressed "cancel" button, it would close XFCE without a warning and would take me back to lightdm to re-login my DE. I repeated the same steps and re-produced this.

Is it something that has to do with engrampa or is it a conflict with XFCE's libraries?

Please do close it or move it to necessary place if it's not considered a bug, but a misconfiguration from XFCE's part.

Cheers.

**Comment by monsta** [comment]
@stefano-k: can be closed I guess - not related to this project
