### ISSUE TITLE
libmate-desktop lets caja crash on non-UTF-8 filenames for background image

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-desktop#112]
Via Debian BTS we received issue DebBTS#746339 [1].

TL;DR; Caja crashes because of a faulty handling of wallpaper pathnames that are encoded in a non-UTF-8 locale. This is already documented in the code [2] as a FIXME it should be addressed soon.

Thanks,
Mike

[1] http://bugs.debian.org/746339
[2] https://github.com/mate-desktop/mate-desktop/blob/master/libmate-desktop/mate-bg.c#L375
##

**Comment by sc0w** [comment]
seeing the debian bug report, I noticed this was fixed in caja 1.12.2, so I think this issue can be closed

**Comment by monsta** [comment]
Oh, and `mate_bg_create_pixmap` was only present in GTK+2 code. It's gone since 1.18.
