### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by philipzae** [mate-desktop/mate-desktop#115]
Please excuse me if this is the wrong place to post this. I'm running Linux Mint Mate and i've noticed that keyboard shortcuts that have similar keys will conflict with each other, like if the mintmenu was assigned to the super key, assigning super key+T for terminal will not function as it will always open up the mintmenu.

**Comment by BikingGlobetrotter** [comment]
I have a similar issue: 
I have a fresh install of Linux Mint 17.1 Rebecca with MATE (x64). I would like to have some keyboard short cuts like in windows, e.g. Lock Screen using Windows + L (Super + L). When I try to change that in the control center, the short cut does not work. 
Furthermore, it is strange that short cut is binded to Mod4+L instead of Super+L.

**Comment by philipzae** [comment]
The workaround i've used to this problem is to assign the mintmenu with Super+Ctrl and then all the other ones work fine.

**Comment by BikingGlobetrotter** [comment]
Hi philipzae,
thank you for your quick reply. How did you do that? I cannot assign mintmenu in the UI for changing the Keyboard Shortcuts.

**Comment by philipzae** [comment]
Right-click on the mintmenu and click Preferences and you'll be able to change the shortcut there.

**Comment by BikingGlobetrotter** [comment]
Thank you very much. But still I like to keep it open as I still consider it to be a bug.

**Comment by sevenskull** [comment]
I can reproduce this bug too.
On cinnamon, everything goes fine, but in mate the key you set for mintmenu, blocks every other global shortcut on mint using combination with this key.
For example: Super + E, for explorer is blocked when using Super for open mint menu.
It seens that when you assign a key for mintmenu, it blocks for everything else.

**Comment by flexiondotorg** [comment]
@monsta This reads like it is a bug in mineMenu. Can you reproduce?

**Comment by monsta** [comment]
Sounds very much like https://github.com/linuxmint/mintmenu/issues/98...

**Comment by monsta** [comment]
Yes, it's there and it needs to be fixed there. Closing this report, please follow https://github.com/linuxmint/mintmenu/issues/98.
