### ISSUE TITLE
hidden panel makes system unusable

### ISSUE THREAD

**Issue by adam-a-smith** [mate-desktop/mate-desktop#116]
(I hope this is the right place to leave this.)

I managed to make the desktop crash in Qiana-64/MATE, and the system became unusable. I then repeated the process using just the OS running from the installation CD.

1) Make or move a panel at the top of the screen.
2) Make a new panel, move it to the top, and make it hidden.

The system starts behaving in a very unstable way after this. Soon, you're just left with a flashing, blank panel at the top of the screen, and no way to undo the damage. What's worse, it's the same after you log back in (though not using the CD, of course)--it seems a way to permanently kill a user's desktop, unless you know how to modify the config files by hand (which I do not--the only way I could figure out to fix this was to reinstall).

**Comment by monsta** [comment]
@stefano-k: can be closed I guess - not related to this project
