### ISSUE TITLE
Add hot corners to MATE

### ISSUE THREAD

**Issue by freemangilgamesh** [mate-desktop/mate-desktop#118]
Unlike Cinnamon, I think Mate is missing this feature.

**Comment by PaulReiber** [comment]
Its now 2019. Hot corners ARE now an expected feature on "traditional" desktops.

MATE still has no straightforward means of handling hot corners.  

This matter should be reopened and resolved.

**Comment by lukefromdc** [comment]
You can do this now with compiz (either version), whose "expo" mode is similar to what Cinnamon does, and compiz works well in MATE just as it did with GNOME 2.
