### ISSUE TITLE
Copy file error with Mate in Vmvare

### ISSUE THREAD

**Issue by crazyi** [mate-desktop/mate-desktop#119]
Recently I decided to upgrade my ubuntu 12.04 to LM17 mate. I fully installed the LM17 mate in vmware and as well as the vm-tools, but I find that I can not copy the file from my host win7 directly to the vmware, however, copying from vmware to my host win7 is perfect.
I tried cinnamon edition, copying from both sides works fine. I also install mate in ubuntu 14.04, still no luck.
The more details can be seen here:
http://forums.linuxmint.com/viewtopic.php?f=90&t=170706
http://forums.linuxmint.com/viewtopic.php?f=18&t=127145

**Comment by monsta** [comment]
@stefano-k: can be closed I guess - not related to this project
