### ISSUE TITLE
Root password input window locks down access to desktop

### ISSUE THREAD

**Issue by Alexonmint** [mate-desktop/mate-desktop#128]
I have a problem with the root password input window that pops up during all root relevant operations.
This window, if activated, locks down the access to anything else outside of it. E.g. switching between different programs, using menus, etc.

If this is a bug I hope it can be fixed. If this is a "feature" intended by the devs than its a pretty inconvenient one, since if used with ibus which is set to another language, it is impossible to switch to a different language if this window is activated. So it must be closed first, the language must be set to standard input and then the root window must be accessed  again.
This is specially annoying if one uses a email program like evolution and must abort the unlocking of the keyring. Evolution will then drop all the passwords for the email accounts and all of them must be re-entered again.

**Comment by monsta** [comment]
This is absolutely not related to ```mate-desktop``` library.
Talk to ```gksu``` developers about it.
