### ISSUE TITLE
Disable Shadow on Compiz

### ISSUE THREAD

**Issue by fingus** [mate-desktop/mate-desktop#140]
It would be very nice if it possible to disable shadow in Compiz, like alt-tab set (see picture)
![shadow](https://cloud.githubusercontent.com/assets/8513401/4932945/22414c4c-6590-11e4-8a1a-1d226068e000.png)

I now there some solution with compiz-manager but i think its not usefull to install many packages to remove one feature (see here http://askubuntu.com/questions/5669/how-to-remove-shadow-from-gnome-panel)

**Comment by monsta** [comment]
This is absolutely not related to ```mate-desktop``` library.
