### ISSUE TITLE
missing icon on mate-color-select

### ISSUE THREAD

**Issue by willysr** [mate-desktop/mate-desktop#147]
Hi

mate-color-select is missing an icon (gcolor2) since mate-themes installed it on /usr/share/icons/ContrastHigh/resolution/apps, while it searched /usr/share/pixmaps.

proposed solution:
- add gcolor2.png to mate-desktop and place it under /usr/share/pixmaps

mate-desktop-1.9.3

**Comment by NiceandGently** [comment]
already done https://github.com/mate-desktop/mate-icon-theme/commit/8b27d64e1999c399c97bd2d94c7d54e609f5c94e

**Comment by NiceandGently** [comment]
marked as can be closed.
@willysr please close

**Comment by willysr** [comment]
Thanks
marking it closed
