### ISSUE TITLE
Unable to register for wiki account

### ISSUE THREAD

**Issue by abeverley** [mate-desktop/mate-desktop#157]
I'm unable to register on http://wiki.mate-desktop.org/. I keep getting "Sorry, but the CAPTCHA wasn't answered correctly" when registering through http://wiki.mate-desktop.org/home?do=register

I've tried it several times, in upper and lower case, and even used the audio to check that I'm getting the letters correct.

I only actually want to make one minor change, maybe you can do it for me:

On page http://wiki.mate-desktop.org/download please add instructions on how to install on Mint 17. It should be the same as Mint 16, but with the package "mint-meta-mate" instead.

Thanks!

**Comment by monsta** [comment]
@stefano-k: please close this...

**Comment by monsta** [comment]
@flexiondotorg: please close - not related to mate-desktop library

also need to figure out how to stop people from filing *general* MATE reports here :confused:
