### ISSUE TITLE
./libmate-desktop/mate-desktop-item.c---->ditem_execute()

### ISSUE THREAD

**Issue by HuangZhiquan** [mate-desktop/mate-desktop#158]
1.open mate-control-center
2.click mate-power-manager or mate-volume-control or nm-connect
3.it will show "Starting ...",but it wouldn't start
4.other applications will have two or more window you can see
i think it's the problem of function ditem_execute()
##

**Comment by NiceandGently** [comment]
Which distro?
Which Mate version?
Can you start mate-control-center from a terminal to see an output?

**Comment by HuangZhiquan** [comment]
ubuntu-mate 1404
I install ubuntu first and then install mate from terminal, nothing i can see when i start mate-control-center from a terminal,it just shows us a notification on panle, then they closes after 15s.
maybe mate should not show that notification when we don't be allowed to open it second

**Comment by flexiondotorg** [comment]
I can't reproduce this Ubuntu MATE 16.04 with MATE 1.16 or on Ubuntu MATE 17.04 with MATE 1.17
