### ISSUE TITLE
session crashes on window-close-not-responding

### ISSUE THREAD

**Issue by vobiscum** [mate-desktop/mate-desktop#159]
After closing an app which probably go not-responding on the close event, the desktop becomes vacant with only one wallpaper.
l'm using lxdm, and the same actions in LXDE will bring up a dialog warning about not-responding and then close duly in seconds.

The .xsession-errors has these lines after mate session defunct:

Window manager warning: Log level 8: Source ID xxx not found when attempting to remove it

w.m.w: Failed to execute child process mate-dialog (no such file or dir...)
w.m.w: Log level 8: g_child_watch_add_full: assertion pid＞0 failed

**Comment by monsta** [comment]
This is absolutely not related to ```mate-desktop``` library.
