### ISSUE TITLE
mate-character-map: restore popup Unicode ID like in Gnome2

### ISSUE THREAD

**Issue by ssrublev** [mate-desktop/mate-desktop#160]
Hello there and thanks for all the work. I am a bit disappointed with a small "mate-character-map" issue: it doesn't display Unicode IDs in "title" popup like it was in Gnome2. Instead, it only prints "Insert special character" ("Вставить специальный символ" in my Russian localization) over each symbol — the same title everywhere. In Gnome2 panel applet, where this applet originates from, Unicode ID was present.

A while ago I wrote about this to "mate-character-map" author: https://github.com/gfunkmonk2/mate-character-map/issues/1 but there was no response. I guess it is quite easy to fix, and this would be very helpful for my works (I am an editor, particularly, in Wikipedia).

Thank you, and please move my request in the proper place, if I placed it wrongly here.

**Comment by stefano-k** [comment]
We are sorry, but mate-character-map was dropped and no more supported. We use gucharmap now.

**Comment by ssrublev** [comment]
Well, I am sorry too, but I could be wrong with the package name... I see no simple way to find correct package name...

I mean the _APPLET_ for __MATE horizontal panel__ — it is included in my full-updated current MATE installation and in Russian is titled "Касса символов 1.8.1"

Here it is, where the cursor is:
![-1](https://cloud.githubusercontent.com/assets/6886166/5944904/a203ad70-a73b-11e4-92cc-3d6c245f3725.png)

This is not "mate-character-map"? Ok, how is it called, and where should I request about it? It comes from Gnome2, I seem to be messed up with the package names...

**Comment by ssrublev** [comment]
"Character Palette", I guess, the correct name, and I'm still unsure of package name

**Comment by ssrublev** [comment]
I looked around more and decided to try to post to "mate-applets", may be it is a right place:
https://github.com/mate-desktop/mate-applets/issues/126
