### ISSUE TITLE
Double clicking in the panel's window list causes window to disappear

### ISSUE THREAD

**Issue by JDougherty** [mate-desktop/mate-desktop#161]
On my MATE panel, I have the Window List which shows all of the windows in a given workspace. If I double click on one of items in the window list, the window that it represents disappears. The process is not killed, but the window is gone from any workspace and does not show up in the window list or the alt+tab list. 

This is easily reproducible on my system. I am running MATE 1.8.1 in Linux Mint 17.1.

**Comment by JDougherty** [comment]
I just wanted to add a video of what is happening:

https://www.youtube.com/watch?v=arh4__5Ymho

It is also apparently the third click, i.e Triple click, that causes the issue, not double click. 

Additionally, despite the window disappearing and no longer being shown in the Window List, if I hover the cursor where it used to be, the cursor acts like the window is still there. I can actually even access the menu of the window, despite it having disappeared.

**Comment by JDougherty** [comment]
Additional information: Clicking on the MATE "Show Desktop Button 1.8.1" in my panel causes the window that disappeared to reappear on the MATE panel. This may be helpful as a workaround for anyone running into this issue.

**Comment by monsta** [comment]
@flexiondotorg: please close - it's about mate-panel, not mate-desktop library

**Comment by JDougherty** [comment]
Do I need to file a bug on a different project?

**Comment by monsta** [comment]
If it still reproducible in 1.10 - yes, it's for **mate-panel** project.
