### ISSUE TITLE
Windows top responding to mouse clicks

### ISSUE THREAD

**Issue by pcjunky** [mate-desktop/mate-desktop#164]
At times my open windows will no longer respond to mouse clicks. Nor do new windows opened. Quick launch bar still does when this happens. To fix I have been logging out. I can click to log out but my mouse won't register a click here either. I have to use the keybaord.

I'm running Linux Mint 17.1 Mate on a Dell D830 with 3 Gigs RAM and Nvidia GPU. This happens with the Nvidia Nouveau or the binary driver just the same.

**Comment by monsta** [comment]
@flexiondotorg: please close - not related to mate-desktop library
