### ISSUE TITLE
Mouse busy (working) icon indicator doesn't always show

### ISSUE THREAD

**Issue by kacernator** [mate-desktop/mate-desktop#171]
When opening application/file/folder from desktop, from mate-menu or from Caja, the mouse icon doesn't change to busy spinning wheel. It just works very rarely with some actions.

Linux Mint 17.1
Mate 1.8.1

**Comment by monsta** [comment]
This is absolutely not related to ```mate-desktop``` library.

**Comment by kacernator** [comment]
OK, I didn´t know that. Can you please help me, where should I report this bug?

Thank you.

**Comment by monsta** [comment]
Is it still reproducible in MATE 1.10?
Also, did it ever work like you described in previous versions?

**Comment by kacernator** [comment]
Yes, in Mate 1.10, when I click on my Home folder icon or Computer icon on desktop, no busy indicator. It is hard to know if you did click right, or application is opening.

**Comment by monsta** [comment]
It seems that it affects only desktop and mintMenu, because when Caja window is already open, clicking on folders or on sidebar elements shows me the busy cursor just fine.

**Comment by kacernator** [comment]
Open shortcuts of files or programs on desktop, the busy cursor works. It dos not work when clicking on Home folder on desktop, on Computer on desktop and on Trash on desktop. Also when no busy indicator is shown, there is no indication on taskbar (Opening ...) either.
