### ISSUE TITLE
mate-screenshot is not using print key

### ISSUE THREAD

**Issue by ghost** [mate-desktop/mate-desktop#172]
Hi team, i'm using fedora 22 spin mate, now i've see that the key "Impr print" is not available with the command "mate-screenshot". now i can't remember if in the past version of mate-desktop this function was available by default.

here is the output of the components 

[root@new-host iplavvia]# rpm -qa |grep -i mate-desktop
mate-desktop-libs-1.10.0-3.fc22.x86_64
mate-desktop-1.10.0-3.fc22.x86_64
[root@new-host iplavvia]# 
[root@new-host iplavvia]# 
[root@new-host iplavvia]# 
[root@new-host iplavvia]# 
[root@new-host iplavvia]# 
[root@new-host iplavvia]# 
[root@new-host iplavvia]# rpm -qa |grep -i mate-screenshot
mate-screenshot-1.10.0-1.fc22.x86_64
[root@new-host iplavvia]# 

regards from chile

**Comment by monsta** [comment]
@flexiondotorg: please close - mate-screenshot is in mate-utils package

optional: try to understand what this report is actually about :laughing:
