### ISSUE TITLE
mate-desktop manpages

### ISSUE THREAD

**Issue by gnugr** [mate-desktop/mate-desktop#175]
The new upstream needs also man pages to handle mpaste and the mate-color-select.
https://alioth.debian.org/scm/browser.php?group_id=100862

**Comment by sunweaver** [comment]
@gnugr: @all: this is the URL, where to obtain the man pages (consider them as drafts): http://anonscm.debian.org/cgit/pkg-mate/mate-desktop.git/commit/?h=debian/experimental&id=6dcf092e86472bc8f3f55d67f66dac9c982c3b8d
