### ISSUE TITLE
touchpad stopped working on upgrade

### ISSUE THREAD

**Issue by utoddl** [mate-desktop/mate-desktop#178]
After upgrading to fedora 22, my synaptics touchpad quit working in MATE. This was eventually resolved (see https://bugzilla.redhat.com/show_bug.cgi?id=1236110) Somehow, the org.mate.peripherals-touchpad touchpad-enabled became false. Setting it to true fixed the issue.

The problem is, there's nothing in System->Preferences->Hardware->Mouse to control this property. I had set just about every combination of values under the Touchpad tab, but none of them control this. Would it be possible (sure it is) to put a checkbox in that dialog to enable the Touchpad in this case? It would have saved me almost a month! Thanks.

**Comment by clefebvre** [comment]
We'll add that in 1.12.

**Comment by utoddl** [comment]
Fantastic. Thank you.

**Comment by monsta** [comment]
@clefebvre: can we consider it fixed in m-s-d/m-c-c already?

**Comment by clefebvre** [comment]
Hi @monsta,

I'm not set up to work on MATE atm unfortunately and although I remembered we talked about that and agreed to put it in... I can't remember actually doing it.

Looking at my commit on 3 finger click support and natural scrolling, I don't think I added that global switch in it.

We're past feature-freeze unfortunately... there's three things to consider here:

- This is safe and very unlikely to create bugs
- This is trivial to implement (it's a one-liner)
- This would need to be translated (we'd introduce a new string for it in the UI)

If it wasn't for the translations, I'd say we should go for it, despite the freeze, and squeeze it in.

I don't really know how translations work here and who's in charge of them and what their availability is.

So all in all, I've no opinion on this. You guys @monsta, @raveit65, @flexiondotorg decide on the best time to implement that and throw it in. Whether it's now, whether it's in a later 1.12.x or whether it's in 1.14.

Sorry @utoddl, I should have done that, it would have taken just a few minutes extra at the time when I worked on touchpad support, but I completely forgot about it..

**Comment by flexiondotorg** [comment]
My vote is add it now.

**Comment by monsta** [comment]
So the only issue is a new string for translation... I think we can add it and push changes to transifex right after that, so that the guys there could translate it before 1.12 release.

**Comment by raveit65** [comment]
why waiting?

**Comment by monsta** [comment]
Ok, there goes https://github.com/mate-desktop/mate-control-center/pull/204

everybody please test it if you can :smile:
