### ISSUE TITLE
mouse cursor not visible on bootup

### ISSUE THREAD

**Issue by maxcel** [mate-desktop/mate-desktop#181]
Linux Mint 17.1 Mate 64bit
Hardware: Biostar A68N-5000 AMD A4-5000 APU with Radeon HD Graphics
Monitor - Benq GW2765 native resolution 2560x1440 set to run at 1920x1080.

Using the default driver "xserver-xorg-video-ati Version 1:7.3.0-1ubuntu3.1" and the monitor set to 2560x1440, the mouse cursor is visible from the login screen onwards and performs normally. If the screen resolution is set to 1920x1080 then the cursor is not visible at any time although the mouse is functioning, as witnessed by items highlighted when the mouse is moved over them and can be selected by mouse clicks (mouse position set the be highlighted by pressing Ctrl key).

By changing the driver to "fglrx-updates Version 2:15.200-0ubuntu0.3" the cursor shows correctly at both resolutions.

The fault is consistent and happens at every boot-up.

**Comment by monsta** [comment]
This is absolutely not related to ```mate-desktop``` library.
