### ISSUE TITLE
xdg-open doesn't seem to work right

### ISSUE THREAD

**Issue by liamdawe** [mate-desktop/mate-desktop#184]
Referencing this issue on the Steam client: https://github.com/ValveSoftware/steam-for-linux/issues/3924#issuecomment-121321920

It should open the file manager using xdg-open, but it tries opening a media player I have installed?

**Comment by infirit** [comment]
In the preferred applications preference look under the system tab to see what the file manager is set as. I suspect this is currently set as the media player (audacious by any change?).

**Comment by liamdawe** [comment]
No, it is set as Caja.

Here: http://i.imgur.com/x3odjKs.png

**Comment by NiceandGently** [comment]
This can only be solved by your distro package maintainer. Your distro should ship a mate-mimeapps.list to set the default mime types.
See http://wiki.mate-desktop.org/distributions#mimeapplist
Please open a report there and ask for it.
@infirit 
Please close, we can't fix that.

**Comment by flexiondotorg** [comment]
@liamdawe You are using Ubuntu MATE right? Which version? I've fixed this issue in 15.10 and could push the "fix" to earlier versions. I'll close this here, I've seen you tweet, because it is not MATE specific.
