### ISSUE TITLE
mate-user-guide.desktop not internatiolized

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-desktop#189]
The mate-user-guide.desktop file needs to be internationalized.

Maybe also the Name= field should be changed from "Help" to "MATE Help".

Greets,
Mike

**Comment by monsta** [comment]
Well, ```user-guide/mate-user-guide.desktop.in.in``` is listed in ```po/POTFILES.in```, so it might be just a case of the latest changes not pushed to Transifex yet...

**Comment by monsta** [comment]
Should be fixed in https://github.com/mate-desktop/mate-desktop/commit/26b41761c10ab28c28757d0c17726c0372bddb57.
