### ISSUE TITLE
Is it possible to revert language update?

### ISSUE THREAD

**Issue by xdevelnet-inc** [mate-desktop/mate-desktop#192]
Hi there!

I am using Linux mint 17.1 (MATE 1.8.1 or MATE 1.8.2), and my system is in ukrainian language.
Now i bought new SSD and installed Linux mint 17.2 with (almost) latest MATE. And what I see? 30% of all words looks horrible, and most annoying word is "проґрама", which should be "програма".

IDK who did such terrible things (like "ґ" char in almost every word) because I can't check translations history at https://www.transifex.com/mate/MATE/, especially (for example) here: https://www.transifex.com/mate/MATE/viewstrings/#uk/caja/2538287

So, I have few questions:

1) Can I revert language update without downgrading to previous MATE version? Which packages I should to (re)install? If it's not possible, how I can do that manually?
2) Is it true, that nobody check translations before using them?

Thanks :)

**Comment by infirit** [comment]
The best thing to do is create an account on transifex amd join the ukrainian language team. There you can update and raise issues. There is also a mailing list for translations, http://ml.mate-desktop.org/listinfo/mate-i18n

**Comment by xdevelnet-inc** [comment]
@infirit
Thank you from fast answer!
I already created accound on transifex and appliet request 4 joining lang team. But is it possible manually edit lang on my system?

**Comment by infirit** [comment]
You can by using ``msgunfmt`` on the installed mo file. It will create a po file which you can edit. Then use ``msgfmt`` to turn it into a mo file again.

These file live in ``/usr/share/locale/``.
