### ISSUE TITLE
scrolling mouse wheel up/down really fast in a window causes to switch workspace in virtualbox

### ISSUE THREAD

**Issue by EvanDPoore** [mate-desktop/mate-desktop#193]
If my mouse is positioned over a window and I'm scrolling rapidly and repeatedly down a page, the workspace switches to the one directly to the right of the current workspace.

This happens in Fedora 22 out of the box. infirit says "It only happens on certain distros and/or setups. I never had this on gentoo with the evdev driver."

**Comment by GiedriusS** [comment]
Where did he say that? Could you link to the other issue? Also, is there any script that could reproduce this e.g. scroll down fast enough?

**Comment by infirit** [comment]
>Where did he say that

Many times on irc.. The only way I could get this behaviour is in a virtualbox vm with debian/fedora. My guess is that the mouse pointer jumps to the bottom right corner where the switcher is located.

**Comment by EvanDPoore** [comment]
I can confirm that this occurs inside VirtualBox and not otherwise. I didn't notice this difference at first because I remove the Workspace Switcher on my primary desktop, but regularly have to deal with virtual machines which don't have my customizations.

I was also able to reproduce the issue with PCLinuxOS (inside VirtualBox). I tested that distro because it is the first one listed on DistroWatch which is not Fedora or Debian based which also had an easy-to-find download for a Mate LiveCD. Based upon this result, I think it's safe to say Gentoo would be in the minority in not being affected.

I can confirm that this only occurs when the Workspace Switcher is pressed up against the bottom right of the screen. Does not occur if it is placed in one of the other corners; does not occur if placed in the middle; does not occur if placed just slightly (perhaps just a pixel) away from the right edge of the screen.

Scrolling up is also affected, though you will instead be switched to the workspace to the left of your current workspace.

I've found a convenient way to reproduce the issue (inside VirtualBox, of course) is to switch to a middle workspace, then navigate caja to /etc and then scroll very quickly down the page, while moving the mouse slightly in any direction (I've determined that this only seems to happen if the mouse is moved slightly while scrolling, which apparently I do accidentally). Turning up your mouse sensitivity may help for reproducing.

**Comment by infirit** [comment]
It does not happen any-more for me with virtualbox 5. Which version are you using @EvanDPoore?

**Comment by EvanDPoore** [comment]
I'm using a release from the 4.x series. It sounds like the issue has been addressed in the 5.x series and isn't a problem with Mate anyway.

**Comment by imran-uk** [comment]
I had this problem with Debian Jessie with the MATE desktop. Turns out I didnt have Guest Additions installed. Once I had installed the linux-headers like this `aptitude install linux-headers-3.16.0-4-amd64` and installed Guest Additions the mouse wheel glitch went away.
