### ISSUE TITLE
Wrong desktop background in 17.2 when changing screen resolution

### ISSUE THREAD

**Issue by greyskier** [mate-desktop/mate-desktop#200]
Since updating to 17.2 I am having a problem when using my laptop for viewing Netflix on my TV. When viewing Netflix I set Monitor Preferences to "Same image in all monitors" and resolution automatically goes to 1024 x 768 as it should. When done with Netflix I uncheck the "Same image" box and set resolution back to 1280 x 800. The Desktop background image is then fractured with about 2 1/2" from the right edge of the screen being a wrap around(?) as if it was the left edge starting over again except about 1" in from the left edge. Logging out and back in as another user (they always see the correct image) and then back in as myself or doing a Shut Down and then starting the laptop up again does not seem to clear the problem. Sometimes doing a Restart after trying those other tactics does bring back the correct image though. Until of course I use Netflix again. I'm just using the default 17.2 background and trying to change to a different background makes no difference.
##

**Comment by flexiondotorg** [comment]
I can't reproduce this issue on Ubuntu MATE 17.04 with MATE 1.17 or Ubuntu MATE 16.04 with MATE 1.16.

**Comment by greyskier** [comment]
Sorry I thought I had closed this thread as it turned out to be an issue of whether or not a TV was plugged into the port on the laptop.
