### ISSUE TITLE
GNOME apps fail to find their icons

### ISSUE THREAD

**Issue by ildar** [mate-desktop/mate-desktop#202]
Some GNOME apps use icons located in /usr/share/icons/gnome/ . But in MATE environment those icons aren't available, hence apps show broken icons.
Is it possible that "icon search paths" completed with the GNOME icons folder?
The apps in trouble are, for example, devhelp, gnome-disks, Baobab etc.
##

**Comment by monsta** [comment]
Which distro/release?
Which versions of baobab, devhelp, gnome-disks?
Were you able to solve the issue manually somehow?

**Comment by flexiondotorg** [comment]
I've not encountered this and no feed from the reporter :-( Closing.
