### ISSUE TITLE
caja crashed when feh image viewer is used

### ISSUE THREAD

**Issue by ghost** [mate-desktop/mate-desktop#205]
Hello mate community i'm not sure if this is a bug, but I've found that caja crashed when feh ( image viewer) is used. first i think so this is happened because I've using kernel 4.3 but later i start my fedora 23 machine with the kernel 4.2 and i give the same results. 

I've report the bug in bugzilla but i think that is better report here in the upstream . regards !!

https://bugzilla.redhat.com/show_bug.cgi?id=1261735

[idviare@new-host-5 ~]$ rpm -qa |grep -i caja
atril-caja-1.10.2-1.fc23.x86_64
caja-schemas-1.10.3-1.fc23.x86_64
caja-sendto-1.10.0-3.fc23.x86_64
caja-extensions-1.10.3-1.fc23.x86_64
caja-extensions-common-1.10.0-3.fc23.noarch
caja-image-converter-1.10.0-3.fc23.x86_64
caja-wallpaper-1.10.0-3.fc23.x86_64
caja-open-terminal-1.10.0-3.fc23.x86_64
caja-actions-1.8.0-2.fc23.x86_64
caja-actions-doc-1.8.0-2.fc23.noarch
caja-1.10.3-1.fc23.x86_64
[idviare@new-host-5 ~]$

**Comment by monsta** [comment]
Not reproducible with feh 2.12 and Caja 1.13 here. That menu item for setting bg does nothing at all, and Caja doesn't crash either. Since there were no requested feedback in the downstream report, I don't see a point in keeping this report open.
