### ISSUE TITLE
Scaling support for HiDPI

### ISSUE THREAD

**Issue by auralon** [mate-desktop/mate-desktop#208]
There is currently no way to adjust scaling, which is often required for HiDPI monitors.
##

**Comment by monsta** [comment]
We won't be able to support HiDPI anyway in the near future as it's simply not supported in GTK+2.

**Comment by auralon** [comment]
It's a shame.  I hope HiDPI support gets prioritised at some point, otherwise Mate could become somewhat insignificant due to unusability.

**Comment by det** [comment]
It's possible to set GDK_SCALE=2 in /etc/environment and then all gtk3 applications look nice, but then mate thinks the the screen is 2x too large and positions panels and new windows in the wrong place or even off-screen. This is using a gtk3 compiled mate 1.12. If this were fixed tere would be a workable solution, even if there was no GUI setting for it.

**Comment by allanlaal** [comment]
the solution by @det is fine if you have 1 monitor, however for a multimonitor setup you need to scale each monitor separately using xrandr:
http://blog.jamiek.it/2015/04/manually-fixing-multiple-screens-with.html

I found calculating the --fb parameter tedius and used arandr to position and calculate the --fb and --pos for me. I then added --scale to every active monitor in that command

**Comment by xdevelnet** [comment]
You can also try to use large fonts as a kludge

**Comment by lf94** [comment]
I actually used MATE on a 133dpi screen (nearly retina) and everything behaved fine...Just had to set the correct dpi.

**Comment by allanlaal** [comment]
the biggest annoyance with this occurs when mixing HiDPI and non-HiDPI screens

**Comment by unoexperto** [comment]
Hey guys, I used to use MATE until I bought new XPS 13 with HiDPI display. I couldn't make Ubuntu MATE 16.10 work with apps I need so I had to switch to Mint Linux 18 where support of HIDPI is implemented with **one switch**. I just noticed that Ubuntu MATE 17.04 is released with happy announcement of GTK3+ support but I don't see any progress with hidpi support. Yeah, I can change font resolution but it's half-measure. UI controls of Chrome browser which I'm using to write this comment are still microscopic. Same goes for most other apps.

Am I missing something ? What should I do ?

**Comment by xdevelnet** [comment]
>Am I missing something ?

you missing the fact that chrome developers does not care about any platform except windows and their own chromeos. If you wish to get chrome work with hidpi, use additional command line option "--force-device-scale-factor=1.5" when executing chrome. You may wish to change "1.5" to your own value for your own monitor.

BTW, I recommend to use chromium.

**Comment by unoexperto** [comment]
@xdevelnet What about size of controls of MATE itself as shown in provided screenshot ?

**Comment by xdevelnet** [comment]
@unoexperto Did you mean size of "close/maximise/minimise" buttons? Unfortunately, I recently sold my HIDPI monitor, therefore I have no idea what is 100% solution in your case. I would recommend you to take a look at editing MATE themes, I guess you can change sizes of these buttons through changing the theme(s).

Also, there is separate configuration(s) for GTK2/3 specific things like toolbar icons. Related links:
https://wiki.archlinux.org/index.php/HiDPI#GUI_toolkits
https://davidjb.com/blog/2012/10/configuring-gtkgnome-toolbar-icon-sizes-and-labels-ubuntu-12-10-and-more/

**Comment by nooryani84** [comment]
@flexiondotorg Do you know if anything is happening here?

I have currently tried fixing the DPI scaling issues with the following:
export GDK_SCALE=2
export GDK_DPI_SCALE=0.5

Thanks go to Martin for the current workaround, it is a lot better than the defaults! :)

This isn't ideal, though from what I understand the Gnome team are working on fractional scaling for Gnome 3.26 , will this be ported to Mate?

Another solution I have heard about is using the default integer scaling then using xrandr as well.  Is there anyone who can confirm if this works?   Maybe this could be added to the Mate Tweak tool until a proper solution is in place?   See link for more info about what I'm talking about [https://wiki.archlinux.org/index.php/HiDPI#GNOME](url)

**Comment by vkareh** [comment]
We now have proper HiDPI support. Closing this, as the focus will now be on more specific issues with it.

**Comment by MartinX3** [comment]
Since 1.18?

**Comment by vkareh** [comment]
@MartinX3 - since 1.20, which was released on February 7th :)

**Comment by MartinX3** [comment]
Thank you. :)
Now I need to wait to get this upgrade. :P
Maybe in Linux Mint 19 :P
In Ubuntu Mate 17.10 isn't it TOI, but I will move that machine to Linux Mint 19 too :)

**Comment by monsta** [comment]
Yes, MATE 1.20 will be in Ubuntu 18.04 and Mint 19.

**Comment by vkareh** [comment]
So far the only release distro that has it (that I know of) is [Solus](https://solus-project.com/)

**Comment by raveit65** [comment]
Next 1.20 upgrade will be in stable fedora 27 release from last year, which use 1.19.x packages already,
because of our switch to 1 year development.

**Comment by killerkalamari** [comment]
For anyone else that got here from a web search while trying to figure out how to change the HiDPI setting, I finally stumbled across it:
System > Preferences > Look and Feel > MATE Tweak
Windows (left column) > HiDPI (Auto-detect), change it to HiDPI

**Comment by raveit65** [comment]
Yes, auto-detection doesn't work for some monitors. I use those settings.
```
[rave@mother ~]$ gsettings get org.mate.interface window-scaling-factor
2
[rave@mother ~]$ gsettings get org.mate.peripherals-mouse cursor-size
24
```
Also this switch for auto-detection of font DPI settings needs to be disabled in mate-appearance-properties.
![mate-appearance-properties-font-settings](https://user-images.githubusercontent.com/961604/39416390-d8fb65ca-4c4c-11e8-867f-a0ff32f17746.jpg)
Otherwise fonts are to huge.
Well, hardware is different ;)

**Comment by marco-fp** [comment]
Does this work with the window borders (close, minimze and maximize buttons), and the topbar aswell?

I have a 2k monitor (lenovo x1 carbon) and setting the DPI higher results in bigger text but everything else is pretty much the same; it's still not a complete solution.

**Comment by raveit65** [comment]
> Does this work with the window borders (close, minimze and maximize buttons), and the topbar aswell?

No, this is on TODO list ;)
This is a left over from https://github.com/mate-desktop/marco/pull/399
You can open a report against marco if you like.

Also, panel icon fixes aren't release.
