### ISSUE TITLE
Stuck with building

### ISSUE THREAD

**Issue by pepa65** [mate-desktop/mate-desktop#210]
While doing ./autogen.sh this package (and several others) complain that some autoconf macros were not found in my aclocal path (or some forbidden ones WERE found).

What can be done?

**Comment by posophe** [comment]
Please be more specific. Which ones ?

**Comment by pepa65** [comment]
Build environment: Ubuntu Mate 15.10, installed: autoconf libtool yelp-tools intltool libglib2.0-dev gtk-doc-tools libxml2-dev libxslt1-dev librarian-dev scrollkeeper libidl-dev libconf-dev libcanberra-gtk-dev libnotify-dev libwnck-dev libfakekey-dev libgtop2-dev libindicator-dev liboobs-1-dev sytem-tools-backends-dev libunique-dev

What builds: mate-common mate-doc-utils marco mate-icon-theme-faenza mate-icon-theme mate-themes mate-user-guide mate-backgrounds mate-user-guide-mallard mate-mime-data 

What doesn't build due to macro problems: mate-desktop mate-applets caja-extensions mate-media mate-power-manager pluma mate-terminal mate-session-manager eom mate-control-center mate-panel mate-screensaver atril mate-notification-daemon mate-sensors-applet mate-utils libmatemixer mate-system-monitor engrampa mate-menus mate-polkit libmateweather libmatekbd mate-character-map mate-calc mate-bluetooth mate-dialogs mate-file-manager-image-converter mate-file-manager-sento libmatewnck libmatecomponent libmatecanvas mate-conf-editor libmateui mate-vfs libmatecomponentui python-mate-desktop libmate python-mate

What doesn't build due to dependencies: mate-settings-daemon mate-netspeed mate-indicator-applet mate-file-manager-open-terminal mate-file-manager-share mate-file-manager-gksu mate-user-share mozo mate-netbook python-caja [couldn't find python-2.7] mate-system-tools 

Other problems: caja mate-keyring mate-university [./README not found] libmatekeyring mate-corba [implicit declaration g_mutex_free] libmatenotify [./Changelog not found] python-corba [./Changelog not found] mate-conf

**Comment by monsta** [comment]
1. Enable source code repositories in ```software-properties-gtk```.
2. ```sudo apt-get build-dep mate-desktop``` (or any other package)

**Comment by pepa65** [comment]
1. I had all source code repos present in sources.list
2. Cool, never realized that you could (have to!) do that. Super! Making me curious how to do that for rpm based distros, or for Arch & co, or for Slackware..! (I guess it might not be as easy everywhere else.)

Everything seems to be building now, except for: mate-applets [ld cannot find -lcpupower] mate-file-manager-open-terminal [libmate/mate-desktop-item.h missing] mate-power-manager mate-university [Makefile.in missing] mate-corba [implicit declaration g_mutex_free] 

Thanks for taking the time to help.

**Comment by monsta** [comment]
I recommend building .deb packages like described in [this article](https://raphaelhertzog.com/2010/12/15/howto-to-rebuild-debian-packages/). It will help to make sure the correct configure flags are set, e.g. like in [cpufreq lib selection](https://github.com/mate-desktop/debian-packages/commit/39142d0be4bff06ef43f399702f8e73a08c7607c) for mate-applets.

The packages that had been dropped from MATE (like ```mate-corba```) or merged into some other packages (like ```mate-file-manager-open-terminal```) are useless to build. There's no need for them these days.

Makefile.in should be auto-generated from Makefile.am during the build.

**Comment by pepa65** [comment]
Thanks, I'll keep that in mind. Great resource!
It works well enough now, happy about this new release. I'm really putting my hopes on MATE for our future desktops, as we're phasing out Gnome classic/fallback/flashback.
