### ISSUE TITLE
xdg-open points to (obsoleted?) mate-open

### ISSUE THREAD

**Issue by TruboXL** [mate-desktop/mate-desktop#212]
Fedora 23 MATE-Compiz

Not really sure I should report here (xdg-open authors are FreeDesktop?),
but seems like others report that kind of problem here, then I followed suit.

> /usr/bin/xdg-open: line 628: mate-open: command not found

This error is triggered from a Steam Python game, Carpe Diem
Something like trying to open up local HTML help page.

A lookup at MATE Forum says mate-open is missing (obsoleted?) and gvfs-open is official replacement
http://forums.mate-desktop.org/viewtopic.php?f=2&t=2012

Though xdg-open do cover gvfs-open but other cases still fallback to the obsoleted mate-open.

I did the
> sudo dnf provides /usr/bin/mate-open

and returns nothing whereas

> sudo dnf provides /usr/bin/gnome-open
> sudo dnf provides /usr/bin/exo-open

did return some packages.

Maybe time for a cleanup by:
1. Following GNOME's open_generic fallback approach
or
2. Following XFCE's approach by putting everything to pass through exo-open

Sorry for the messy report.

**Comment by raveit65** [comment]
@TruboXL 
Well, mate-open is droped since a long time, so we can't fix that here.
Upstream needs to adjust theie script to follow our change.
We are still wondering about that xdg-open upstream support Mate.
Can you please open a report at freedesktop and link them here?

**Comment by raveit65** [comment]
PS: Mate use simply the xdg-open command.
This should be reflected by their script.

**Comment by TruboXL** [comment]
Done! Not really sure I reported it correctly since their list of products (xdg related) in the Bugzilla page all look similar enough @.@

https://bugs.freedesktop.org/show_bug.cgi?id=93442

**Comment by raveit65** [comment]
Thank you :)
It's the right product.
```
[root@mother rave]# dnf provides /usr/bin/xdg-open
Die letzte Prüfung auf abgelaufene Metadaten wurde vor 2:25:48 auf Fri Dec 18 14:38:40 2015 ausgeführt.
xdg-utils-1.1.1-1.fc22.noarch : Basic desktop integration functions
Quelle      : @System
```

**Comment by TruboXL** [comment]
#### Ok so I guess the MATE side is fixed and done. End-of-story!
##### (At least open_generic is providing back up in case mate-open is N/A)
===
For the Steam game side (if you guys interested), it seems somebody had reported it...
ValveSoftware/steam-for-linux#3985

Link to that game discussion:
http://steamcommunity.com/app/423880/discussions/0/494632768628067586/

Sorry devs if this is a bumper to you... :fearful:

**Comment by monsta** [comment]
Yes, it's fixed upstream now.
