### ISSUE TITLE
MATE Notification center

### ISSUE THREAD

**Issue by Mikaela** [mate-desktop/mate-desktop#213]
This might be a wrong issue tracker, but I don't know any better place.

It would be nice if there was some kind of MATE Notification center storing notifications from the apps, currently there are only small popups which disappear after some time.

For example [Google Chrome/Chromium removed their own notification centre in favour of system one.](https://blog.chromium.org/2015/10/streamlining-notifications-on-desktop.html)

**Comment by raveit65** [comment]
see https://github.com/mate-desktop/mate-notification-daemon/issues/74

**Comment by Mikaela** [comment]
Ah, so there was already issue and proper place. Thanks :)
