### ISSUE TITLE
MATE crashes upon opening LibreOffice Calc

### ISSUE THREAD

**Issue by jeenuv** [mate-desktop/mate-desktop#216]
As subject, I find the crash on my AMD64 laptop, running 17.3. I had previously [posted](http://forums.mate-desktop.org/viewtopic.php?f=7&t=3680&p=11436#p11436) about this in the forums, but hasn't got any responses. I've the [output from `lshw`](http://forums.mate-desktop.org/download/file.php?id=483) attached therein, but I'm happy give more information if you need it.

**Comment by monsta** [comment]
This is a repository with mate-desktop **library**, which is just one of the components of the whole desktop. If you're not sure which MATE component could be causing the problem, please use your distro's support forum first. Linux Mint forums are a nice place BTW. :smile:
