### ISSUE TITLE
Window moves with alt-tab

### ISSUE THREAD

**Issue by twirrim** [mate-desktop/mate-desktop#217]
I'm not sure if this is the right application to file this against or not.  It's difficult as someone not involved in the Mate project to unravel that.

With Mate 1.8.2 installed on both Ubuntu 12.04 and 14.04 I've found that alt-tabbing to a window causes it to jump from whatever screen it is on, over to the current screen.

E.g. I usually have my email client on the right display, with terminal and browser on my left display.  If I use alt-tab to select thunderbird, it instantly moves over to my current display, which is never really what I want.

It's done it to me a few times under other circumstances too, but not enough that I have a solid idea of "this triggers it", but it seems like if thunderbird does anything to steal focus, e.g. a calendar event pops up, it'll often do it then too.

**Comment by monsta** [comment]
We don't support 1.8 these days. Please try 1.12.
The window manager is [Marco](https://github.com/mate-desktop/marco).
