### ISSUE TITLE
MATE Crashes on VirtualBox and Instances of Inkscape running

### ISSUE THREAD

**Issue by Kogurex** [mate-desktop/mate-desktop#219]
Hi!

I'm using Debian 8 and Mate 1.8.1

Sometimes when i open Inkscape while i'm running an Windows 7 VM, MATE crashes and returns me after several seconds to login screen, losing all changes made to every window opened.

The /var/log/messages at the time of this happening comes below:

`Mar 24 16:04:39 LOCALFROST org.mate.panel.applet.WnckletFactory[2172]: wnck-applet: Fatal IO error 11 (Recurso no disponible temporalmente) on X server :0.
Mar 24 16:04:39 LOCALFROST org.mate.panel.applet.NotificationAreaAppletFactory[2172]: notification-area-applet: Fatal IO error 11 (Recurso no disponible temporalmente) on X server :0.
Mar 24 16:04:39 LOCALFROST org.a11y.atspi.Registry[2229]: XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
Mar 24 16:04:39 LOCALFROST org.a11y.atspi.Registry[2229]: after 34657 requests (34657 known processed) with 0 events remaining.
Mar 24 16:04:40 LOCALFROST org.a11y.atspi.Registry[2126]: XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
Mar 24 16:04:40 LOCALFROST org.a11y.atspi.Registry[2126]: after 34663 requests (34663 known processed) with 0 events remaining.
Mar 24 16:04:40 LOCALFROST org.mate.panel.applet.CPUFreqAppletFactory[2172]: mate-cpufreq-applet: Fatal IO error 11 (Recurso no disponible temporalmente) on X server :0.
Mar 24 16:04:40 LOCALFROST org.mate.panel.applet.MultiLoadAppletFactory[2172]: multiload-applet-2: Fatal IO error 11 (Recurso no disponible temporalmente) on X server :0.
Mar 24 16:04:40 LOCALFROST org.mate.panel.applet.ClockAppletFactory[2172]: clock-applet: Fatal IO error 11 (Recurso no disponible temporalmente) on X server :0.
Mar 24 16:04:43 LOCALFROST ca.desrt.dconf[2172]: g_dbus_connection_real_closed: Remote peer vanished with error: Underlying GIOStream returned 0 bytes on an async read (g-io-error-quark, 0). Exiting.
Mar 24 16:04:44 LOCALFROST org.gtk.Private.AfcVolumeMonitor[2172]: g_dbus_connection_real_closed: Remote peer vanished with error: Error al enviar el mensaje: Tubería rota (g-io-error-quark, 44). Exiting.
Mar 24 16:04:44 LOCALFROST org.gtk.vfs.Daemon[2172]: A connection to the bus can't be made
Mar 24 16:04:44 LOCALFROST org.gtk.vfs.Daemon[2172]: g_dbus_connection_real_closed: Remote peer vanished with error: Underlying GIOStream returned 0 bytes on an async read (g-io-error-quark, 0). Exiting.
Mar 24 16:04:44 LOCALFROST org.gtk.Private.GoaVolumeMonitor[2172]: g_dbus_connection_real_closed: Remote peer vanished with error: Error al enviar el mensaje: Tubería rota (g-io-error-quark, 44). Exiting.
Mar 24 16:04:44 LOCALFROST org.gtk.Private.UDisks2VolumeMonitor[2172]: g_dbus_connection_real_closed: Remote peer vanished with error: Underlying GIOStream returned 0 bytes on an async read (g-io-error-quark, 0). Exiting.
Mar 24 16:04:45 LOCALFROST org.gtk.Private.MTPVolumeMonitor[2172]: g_dbus_connection_real_closed: Remote peer vanished with error: Error al enviar el mensaje: Tubería rota (g-io-error-quark, 44). Exiting.
Mar 24 16:04:45 LOCALFROST org.gtk.Private.GPhoto2VolumeMonitor[2172]: g_dbus_connection_real_closed: Remote peer vanished with error: Error al enviar el mensaje: Tubería rota (g-io-error-quark, 44). Exiting.
Mar 24 16:04:45 LOCALFROST org.gtk.vfs.Daemon[2172]: g_dbus_connection_real_closed: Remote peer vanished with error: Underlying GIOStream returned 0 bytes on an async read (g-io-error-quark, 0). Exiting.
Mar 24 16:04:46 LOCALFROST org.a11y.Bus[2120]: g_dbus_connection_real_closed: Remote peer vanished with error: Underlying GIOStream returned 0 bytes on an async read (g-io-error-quark, 0). Exiting.
Mar 24 16:04:46 LOCALFROST org.a11y.Bus[2172]: g_dbus_connection_real_closed: Remote peer vanished with error: Underlying GIOStream returned 0 bytes on an async read (g-io-error-quark, 0). Exiting.
Mar 24 16:04:48 LOCALFROST kernel: [26933.029872] traps: VirtualBox[2940] general protection ip:7f136246aa8d sp:7ffc97fc97c0 error:0 in libc-2.19.so[7f1362433000+1a2000]
Mar 24 16:04:49 LOCALFROST kernel: [26933.215564] device eth0 left promiscuous mode
Mar 24 16:04:49 LOCALFROST kernel: [26933.230293] vboxnetflt: 0 out of 306220 packets were not sent (directed to host)
Mar 24 16:04:55 LOCALFROST org.a11y.Bus[8438]: Activating service name='org.a11y.atspi.Registry'
Mar 24 16:04:55 LOCALFROST org.a11y.Bus[8438]: Successfully activated service 'org.a11y.atspi.Registry'
Mar 24 16:04:55 LOCALFROST org.a11y.atspi.Registry[8444]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
Mar 24 16:05:10 LOCALFROST org.a11y.Bus[8494]: Activating service name='org.a11y.atspi.Registry'
Mar 24 16:05:10 LOCALFROST org.a11y.Bus[8494]: Successfully activated service 'org.a11y.atspi.Registry'
Mar 24 16:05:10 LOCALFROST org.a11y.atspi.Registry[8551]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
Mar 24 16:05:11 LOCALFROST org.gtk.Private.UDisks2VolumeMonitor[8494]: index_parse.c:191: indx_parse(): error opening /media/aoryu/AoryuShawn/BDMV/index.bdmv
Mar 24 16:05:11 LOCALFROST org.gtk.Private.UDisks2VolumeMonitor[8494]: index_parse.c:191: indx_parse(): error opening /media/aoryu/AoryuShawn/BDMV/BACKUP/index.bdmv
Mar 24 16:05:13 LOCALFROST org.gtk.Private.AfcVolumeMonitor[8494]: Volume monitor alive
Mar 24 16:05:15 LOCALFROST org.mate.panel.applet.CPUFreqAppletFactory[8494]: (mate-cpufreq-applet:8627): GLib-GObject-CRITICAL **: g_value_get_object: assertion 'G_VALUE_HOLDS_OBJECT (value)' failed
Mar 24 16:05:49 LOCALFROST org.blueman.Mechanism[1536]: Exception AttributeError: "'NoneType' object has no attribute 'stdout'" in <bound method Tee.__del__ of <__main__.Tee object at 0x7f28f6fc2750>> ignored
Mar 24 16:05:49 LOCALFROST org.blueman.Mechanism[1536]: Starting blueman-mechanism
Mar 24 16:05:49 LOCALFROST org.blueman.Mechanism[1536]: loading Config
Mar 24 16:05:49 LOCALFROST org.blueman.Mechanism[1536]: loading Network
Mar 24 16:05:49 LOCALFROST org.blueman.Mechanism[1536]: loading Ppp
Mar 24 16:05:49 LOCALFROST org.blueman.Mechanism[1536]: loading RfKill
Mar 24 16:05:49 LOCALFROST org.blueman.Mechanism[1536]: Exiting
Mar 24 16:09:09 LOCALFROST kernel: [27193.856628] device eth0 entered promiscuous mode`

Not always happen but 10 times or more i think it maybe will crash for anyone else...
##

**Comment by flexiondotorg** [comment]
I can't reproduce this.

**Comment by monsta** [comment]
> MATE crashes and returns me after several seconds to login screen

This is not MATE crash, it's X server crash. The log messages hint about it: apps are trying to talk to X server, but it's gone.

I wonder why this report wasn't opened on Debian bug tracker instead.
