### ISSUE TITLE
Using a serial of 0 makes mate-settings-deamon fail to start

### ISSUE THREAD

**Issue by Flamefire** [mate-desktop/mate-desktop#220]
I'm on a laptop with an external VGA monitor on Linux Mint 17.3. Mate-desktop keeps adding the monitors to my existing monitors.xml in which it sets the laptops monitor serial to 0x00000000.
After a relogin the designs are the default and mate-settings-deamon cannot start. I can fix this by manually setting the serial to non-zero values (like 0x1) and running `sudo su; mate-settings-daemon&` or after a relogin by beeing lucky that the monitors.xml is not rewritten.

My monitors.xml looks like this:

```
<monitors version="1">
  <configuration>
      <clone>no</clone>
      <output name="LVDS-1-0">
          <vendor>LGD</vendor>
          <product>0x01e9</product>
          <serial>0x00000001</serial>
          <width>1920</width>
          <height>1080</height>
          <rate>60</rate>
          <x>0</x>
          <y>0</y>
          <rotation>normal</rotation>
          <reflect_x>no</reflect_x>
          <reflect_y>no</reflect_y>
          <primary>no</primary>
      </output>
      <output name="VGA-1-0">
          <vendor>FUS</vendor>
          <product>0x07d3</product>
          <serial>0x0000af9d</serial>
          <width>1920</width>
          <height>1200</height>
          <rate>60</rate>
          <x>1920</x>
          <y>0</y>
          <rotation>normal</rotation>
          <reflect_x>no</reflect_x>
          <reflect_y>no</reflect_y>
          <primary>no</primary>
      </output>
      <output name="HDMI-1-0">
      </output>
      <output name="DisplayPort-1-0">
      </output>
  </configuration>
</monitors>
```

I could not find where the serial is actually used and why a 0 value causes this behaviour. I just found it to work by experimenting a long time...
##

**Comment by flexiondotorg** [comment]
The issue should have been raised in:

* https://github.com/mate-desktop/mate-settings-daemon

**Comment by flexiondotorg** [comment]
If this issue still exists please raise it in https://github.com/mate-desktop/mate-settings-daemon. Thanks :-)
