### ISSUE TITLE
Update MATE Icon in About MATE Dialog

### ISSUE THREAD

**Issue by willysr** [mate-desktop/mate-desktop#221]
Please update the MATE ICON in About MATE dialog.
it's blur and not in high resolution

**Comment by monsta** [comment]
@raveit65: can you please check mate and menta icon themes? I see the issue only with these two - looks like the icon is only available in small size there.

**Comment by willysr** [comment]
Fixed in 6c4218ebe2b67a262e30d166a276dd8197042308
