### ISSUE TITLE
l10n/zh_CN: incomplete translation credits

### ISSUE THREAD

**Issue by MingcongBai** [mate-desktop/mate-desktop#222]
I have just realized the `traslation-credits` in `po/zh_CN.po` is incomplete so I've fixed that according to the `zh_CN.po` file header.

Please do pull the latest change on Transifex...

**Comment by raveit65** [comment]
We did yesterday a pull from transiflex for  1.14 release (today) and tarballs are fixed.
Sorry, next sync with transiflex will happen for releasing 1.14.1 packages.

**Comment by MingcongBai** [comment]
That's fine, just feeling that I should at least report it...
2016年4月8日 下午4:40，"Wolfgang Ulbrich" <notifications@github.com>写道：
