### ISSUE TITLE
Change sound volume in dB, not in percent

### ISSUE THREAD

**Issue by scytho** [mate-desktop/mate-desktop#223]
Sound volume in Mate changes in steps of 5%, at least when you use the mouse wheel on the volume thing in the panel. That leads to steps from 1,34dB (100% → 94%) up to (9% → 4%) 18,06dB, which is pretty annoying. Volume should be changed in dB, for example in steps of 2dB or less. It would be very nice to have the possibility to change it, but the important thing here is: dB, not percent.
##

**Comment by scytho** [comment]
By the way, 49% isn’t -18,07dB, as the volume control states, it’s -3,1dB (10*log(0,49)).

**Comment by flexiondotorg** [comment]
This issue should have been raised in:

  * https://github.com/mate-desktop/mate-panel

**Comment by flexiondotorg** [comment]
If this issue still exists, please raise the issue in https://github.com/mate-desktop/mate-panel

**Comment by raveit65** [comment]
> If this issue still exists, please raise the issue in https://github.com/mate-desktop/mate-panel

volume na-tray applet is part of mate-media package :-)

**Comment by scytho** [comment]
@sparkida: What does that commit do?

**Comment by sparkida** [comment]
@scytho you can ignore, I don't know how that happened
