### ISSUE TITLE
mate-tweak dependencies incomplete

### ISSUE THREAD

**Issue by wplapper** [mate-desktop/mate-desktop#224]
I reported this issue on https://bugs.launchpad.net/ubuntu/+source/mate-tweak/+bug/1576697. I do not know, if I should report here as well.

Anyway:
mate-tweak needs "gi.require_version('Gdk', '3.0')" which is satified by package gir1.2-gtk-3.0. This package is not in the dependency list of mate-tweak.

Here is the current dependency list:
*mate-tweak depends on
    compton
    dconf-cli
    gir1.2-notify-0.7
    mate-desktop-common
    mesa-utils
    python-gobject-2
    python3
    python3-pkg-resources
    python3-psutil
    x11-xserver-utils
    zenity

uname -r: 4.4.0-21-generic (xenial 1604)

lsb_release -rcid:
Distributor ID: Ubuntu
Description: Ubuntu 16.04 LTS
Release: 16.04
Codename: xenial

apt-cache policy mate-tweak:
mate-tweak:
  Installed: 3.5.10-1
  Candidate: 3.5.10-1
  Version table:
 *** 3.5.10-1 500
        500 http://ie.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        500 http://ie.archive.ubuntu.com/ubuntu xenial/universe i386 Packages
        100 /var/lib/dpkg/status

ProblemType: Bug
DistroRelease: Ubuntu 16.04
Package: mate-tweak 3.5.10-1
ProcVersionSignature: Ubuntu 4.4.0-21.37-generic 4.4.6
Uname: Linux 4.4.0-21-generic x86_64
ApportVersion: 2.20.1-0ubuntu2
Architecture: amd64
CurrentDesktop: MATE
Date: Fri Apr 29 14:40:08 2016
InstallationDate: Installed on 2016-04-24 (4 days ago)
InstallationMedia: Ubuntu-Server 16.04 LTS "Xenial Xerus" - Release amd64 (20160420.3)
PackageArchitecture: all
SourcePackage: mate-tweak
UpgradeStatus: No upgrade log present (probably fresh install)

Part2:
If package gir1.2-gtk-3.0 is not installed and mate-tweak is called from the command line, it produces the following error message:
Traceback (most recent call last):
  File "/usr/bin/mate-tweak", line 39, in <module>
    gi.require_version('Gdk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gdk not available

Installing gir1.2-gtk-3.0 remedies the situation and mate-tweak starts ok.

**Comment by monsta** [comment]
We don't maintain it here. Please file a report at https://bitbucket.org/ubuntu-mate/mate-tweak
