### ISSUE TITLE
Support for grid allignment

### ISSUE THREAD

**Issue by Yanpas** [mate-desktop/mate-desktop#228]
Current allignment is unusable, add support for grid
![_2016-06-10_18-29-11](https://cloud.githubusercontent.com/assets/7345761/15969557/4661821c-2f39-11e6-9fb8-a63b63025d0f.png)
##

**Comment by omento** [comment]
+1 on this. I don't like putting these in my desktop, but when I'm working on temporary stuff and need quick access that's where I put them. My not a fan of messy desktops, and the current alignment issues with MATE don't help solve this too much.

**Comment by flexiondotorg** [comment]
Duplicate of https://github.com/mate-desktop/caja/issues/373
