### ISSUE TITLE
double click on file index.theme gives error "could not display - the location is not a folder"

### ISSUE THREAD

**Issue by erikdubois** [mate-desktop/mate-desktop#232]
I am working a lot with icons and their design.
I need to be able to open index.theme as a file in let us say sublime text.

Linux Mint 18 mate presents us a blank file. I guess there is no mime connection.
I tried to fix that by adding more mime definitions in my icon theme. No solution there.

I tried looking at Cinnamon and look for differences between both systems. But I am in over my head here.

Now I am wondering if it is something that is not included in mate.
I am more a linux mint 18 cinnamon user. There we can open this file.

Hope you can shed some light into this matter.

ps permissions on the file are rw-r--r-- like all the other files.

![index theme](https://cloud.githubusercontent.com/assets/10594806/16539452/147e1988-4044-11e6-97d9-0ab9aba025db.png)
##

**Comment by doubledogdare610** [comment]
Try to open it within a command line. If you can open via command line, then it is an issue with caja.
Report the issue here: https://github.com/mate-desktop/caja

**Comment by flexiondotorg** [comment]
Fixed with https://github.com/mate-desktop/caja/commit/91dcd8a19665b6738f8304db127f45b503e00ce3
