### ISSUE TITLE
Dragging icon on desktop 1.16.0-1 past right side of screen causes glitch scrolling

### ISSUE THREAD

**Issue by snthaou** [mate-desktop/mate-desktop#235]
Please forgive me if I am in the wrong place, I tried to look around to see if there was a report of this already. I'm using up to date Arch Linux and had not had this problem until recently. If my desktop is visible and I click and hold an icon on the desktop, and touch the right side of my screen, the expected action would be for nothing to happen, however the desktop begins to scroll in a strange manner. Icons on the left side of the screen are now "pushed" off the edge. Also happens in Caja.

![screenshot at 2016-09-27 15-40-38](https://cloud.githubusercontent.com/assets/22482932/18890612/e03574a2-84cf-11e6-9249-0f255fcc930a.png)
##

**Comment by nokangaroo** [comment]
This is an issue in caja, not mate-desktop; downgrading to caja-1.14.2 solves it for me.

**Comment by monsta** [comment]
Yes, it was a regression in Caja 1.16.0 (https://github.com/mate-desktop/caja/issues/659). It was fixed in 1.16.1.
