### ISSUE TITLE
black caja filename color in icon view with dark background and gtk2

### ISSUE THREAD

**Issue by nokangaroo** [mate-desktop/mate-desktop#237]
The font color of the filenames in icon view does not change to white with a dark caja
background color. The gtk2 version requires a compilation check for "intensity". I 
originally posted this in the caja issues but it belongs here. A more correct form of
the patch posted there would be something like
```
--- mate-desktop-1.16.0/libmate-desktop/mate-bg.c	2016-07-02 10:54:50.000000000 +0200
+++ mate-desktop-1.16.0/libmate-desktop/mate-bg.c	2016-10-14 18:43:00.174255800 +0200
@@ -1327,9 +1327,15 @@
 		g_object_unref (pixbuf);
 	}
 
+#if GTK_CHECK_VERSION (3, 0, 0)
 	intensity = ((guint) (color.red * 65535) * 77 +
-		     (guint) (color.green * 65535) * 150 +
-		     (guint) (color.blue * 65535) * 28) >> 16;
+			(guint) (color.green * 65535) * 150 +
+			(guint) (color.blue * 65535) * 28) >> 16;
+#else
+	intensity = (color.red * 77 +
+			color.green * 150 +
+			color.blue * 28) >> 16;
+#endif
 
 	return intensity < 160; /* biased slightly to be dark */
 }
```
which should not break the gtk3 build. (The original file seems to mix spaces and tabs).

**Comment by raveit65** [comment]
The way to bring in changes is to do a pull request.
Thank you.

**Comment by raveit65** [comment]
Btw. this breaks fg color on light backgrounds.
