### ISSUE TITLE
Entire desktop locks up with rabbitVcs commit

### ISSUE THREAD

**Issue by Moosikins** [mate-desktop/mate-desktop#239]
Using Mate 1.16 with recently update Fedora 24 running a VM under virtualbox 5.1.8

Have Thunar file manager installed, open that up and do a right-click/commit (using SVN repository).

Sometimes, but not always, I get a complete lock-up of the desktop.  It is so complete that the only way to fix it is to kill the VM.  I cannot click on anything in the desktop to get to a terminal window to kill some errant process, can't click in the control panel to check what is going on. Absolutely nothing.  

I've started to do commits via the command line in case I have some unsaved goodies somewhere.  I can examine what's changed and do a graphical diff of changed files but hit the commit button and it locks up.  It does do the SVN commit before locking up.

I am not sure if this is an thunar, RabbitVCS, or SVN problem but given that the desktop is rendered unusable, Mate has an issue somewhere.

I don't know how to document this for you or which logs will be useful.  Ideas?

**Comment by monsta** [comment]
Please do some research first, if you're not sure which app or library is responsible for the bug.
