### ISSUE TITLE
URL is not centered in MATE-About-Dialog

### ISSUE THREAD

**Issue by zensubz** [mate-desktop/mate-desktop#240]
There is a small issue with MATE-About-Dialog - the URL appears not-centered if MATE Desktop is compiled against Gtk3, whereas it shows up correctly if it is compiled against Gtk2. Although this is just a cosmetic thing, but it feels quite odd to see the URL appear in the left rather than in the center.

I have uploaded the screenshots, and here are the links: 
MATE-Desktop Gtk2: http://imgur.com/n1UVuYe
MATE-Desktop Gtk3: http://imgur.com/9iJqzl4

Is there any workaround possible..? Thanks.

**Comment by monsta** [comment]
Ok, it's fixed now with https://github.com/mate-desktop/mate-desktop/pull/254. We'll pick it for 1.16.x releases as well.

**Comment by monsta** [comment]
Fix released in 1.18.0 and 1.16.2.
