### ISSUE TITLE
conflict between gnome x mate

### ISSUE THREAD

**Issue by ViniciusBRodrigues** [mate-desktop/mate-desktop#241]
Take a look in "extrair" window here: https://i.imgsafe.org/cb4142e581.png

There are clear adwaita stuffs conflicting there. Seems like nautilus, but i'm using caja (nautilus is doesn't installed). I also didn't install Gnome in my system.

openSUSE 42.2 Leap

**Comment by monsta** [comment]
What you see there is the standard GTK+3 dialog for opening or saving files.
