### ISSUE TITLE
icon not displayed for Audacious 3.7.1 in MATE 1.12.1 on Gentoo

### ISSUE THREAD

**Issue by dcljr** [mate-desktop/mate-desktop#243]
First time GitHub user, so bear with me... (Let me know if I should be reporting this somewhere else.)

I just installed Audacious 3.7.1 under the MATE desktop 1.12.1 on a reasonably current Gentoo Linux system ("world" updated c. 2016-12-22). The application's icon -- /usr/share/icons/hicolor/{48x48,scalable}/apps/audacious.{png,svg} -- is not showing up anywhere it's supposed to be: in the Applications > Sound & Video menu (the application is there and can be launched fine), in the panel's Workplace Switcher, in the ALT-TAB switcher, or even in the application's own window.

I know both versions of the icon exist and are not corrupt because I see their preview images when choosing an icon for the menu entry via Edit Menus. After choosing the icon, however, the icon doesn't show up in the Launcher Properties, and is not visible anywhere ele it should be.

I'm stumped.

**Comment by flexiondotorg** [comment]
You should probably report this against Gentoo because:

  * It is possible the Audacity package is not correctly installing the
.desktop files for Audacity
  * MATE 1.12 is no longer supported. The current stable release is MATE
1.16.

Regards, Martin.

**Comment by dcljr** [comment]
Bizarrely, the icon started showing up (everywhere except the panel Workplace Switcher) yesterday -- after about 5 reboots, in the normal course of using my system.

I have no explanation for why this happened, although I did do an 'emerge --sync' and update/reinstall a handful of (AFAIK completely unrelated) packages in the meantime. Weird...

(Someone can close this issue now.)
