### ISSUE TITLE
Non-mate themes not "seen"

### ISSUE THREAD

**Issue by burdi01** [mate-desktop/mate-desktop#250]
Slackware64 Current: I installed Mate 1.17.2 as provided by http://slackware.uk/msb/current/latest/x86_64/ as the 2nd desktop alongside XFCE.
The Appearance Preferences do not "see" the non-Mate themes.
After setting e.g. in the dconf-editor org > mate > desktop > interface > gtk-theme to e.g. Clearlooks-Phenix that theme turns out to be fully functional though.
So why are the non-Mate themes not "seen"?

**Comment by monsta** [comment]
A theme only appears in the main view of mate-appearance-properties if it includes both GTK+ theme and window border theme. Hint: "Customize" button will show all the other themes.
