### ISSUE TITLE
Use mouse click to select the active window from [ALT]+[TAB] thumbnails

### ISSUE THREAD

**Issue by PapayaMedia** [mate-desktop/mate-desktop#253]
Once I press [ALT]+[TAB], I'd like to be able to click any of the thumbnails to make it the active window. 

This is the normal behavior in OSX and in XFCE... and I find it very useful.

**Comment by monsta** [comment]
This has nothing to do with mate-desktop *library*, please file a report for [Marco](https://github.com/mate-desktop/marco/issues/), the window manager
