### ISSUE TITLE
Best practices for receiving update notifications?

### ISSUE THREAD

**Issue by slackjaw** [mate-desktop/mate-desktop#255]
Hi All,
Using Mate 1.16.1 on CentOS 7.3, moving from CentOS 6.8 and gnome 2.  No amount of googling has revealed to me how to get Mate to show notifications that updates are pending.  This used to be handled by /usr/bin/gpk-update-icon in gnome-packagekit.  Is there a replacement or port available?

**Comment by raveit65** [comment]
There is no replacement from Mate side for gnome-packagekit but it is available in centos7.
Another solution is to use yumex from epel repo and configure like to use it in session auto-start.
It can be used with a update notification icon in na-tray.
See options in yumex preferences how to config this..
![yumex-centos](https://cloud.githubusercontent.com/assets/961604/24134835/1df823a0-0e07-11e7-9dce-7d81943c46c5.png)

PS: please use fedora forum for questions to use MATE from epel7 repo.
Github is for bug reporting and not a support line.
Sorry we'are a small team
