### ISSUE TITLE
icon theme inheritance doesn't work for select icons

### ISSUE THREAD

**Issue by ushoewai** [mate-desktop/mate-desktop#258]
Please let me know if this bug belongs somewhere else ...

So, the freedesktop.org icon theme specification allows one icon theme to inherit from another icon theme. This allows, for example, "light" icon themes to be created ... such icon themes may have dozens of custom icons, but then fall back to another icon theme for the hundreds of additional icons that are needed for a complete icon set.

The fallback mostly works, except for a few sporadic exceptions. See comparison image below for examples (this is of the Print Preview view of Pluma) -- the gtk-close and dnd-multiple icons show as broken in the light theme ...

![comparison](https://cloud.githubusercontent.com/assets/26843957/24582300/8c51170c-16fa-11e7-9113-3aadf250403f.png)

This "light" theme (for testing purposes) is merely composed of a directory -- /usr/share/icons/mate-light -- containing a copy of index.theme from the mate icon theme, with the "Name" changed to "MATE-Light" (and the name localizations removed), and Inherits=MATE added. The icons should be identical, but as the screen captures show, they're not.

**Comment by raveit65** [comment]
Inherits=mate
see https://github.com/mate-desktop/mate-icon-theme/blob/master/menta/index.theme#L4

**Comment by ushoewai** [comment]
oh, i guess it goes based upon the folder name, rather than the name specified in index.theme

sorry about noise!
