### ISSUE TITLE
Please backport some commits to 1.18.x series (fix mate-tweak 17.10.x series)

### ISSUE THREAD

**Issue by ThanosApostolou** [mate-desktop/mate-desktop#272]
#### Expected behaviour
mate-tweak 17.10.x series working properly

#### Actual behaviour
mate-tweak 17.10.x series give core dump

#### Steps to reproduce the behaviour
use mate-tweak 17.10.x series with mate-desktop 1.18.0, then changing panel layouts results in core dumped.

#### MATE general version
1.18

#### Package version
1.18.0

#### Linux Distribution
arch, antergos (in manjaro mate-desktop is now built over the latest commits in order to solve the problem)

New mate-tweak versions give "core dumped" to distributions with mate-desktop 1.18.0. I believe the commit that fixes it is that: https://github.com/mate-desktop/mate-desktop/commit/e6444114f81750cc18f08f6fd84af121910c0dda.

However, not all distributions are aware of that and for example in arch, mate-desktop is in version 1.18.0 while mate-tweak is in version 17.10.x at AUR and it's unusable. In manjaro the maintainer has built a mate-desktop over the latest commits and the problem is fixed.

I believe it would be easier for distributions to include the fixes if you did a fix release, like mate-desktop 1.18.1 instead of trying to contact the maintainers and ask them to build mate-desktop over latest snapshots.

**Comment by raveit65** [comment]
Please use the template for filing out reports.
This will increase the chances that someone will work on this report.
Try again.

**Comment by ThanosApostolou** [comment]
Ok done. Tell me if more info is needed.

**Comment by monsta** [comment]
Apparently mate-tweak relies on patched mate-desktop in Ubuntu. Inviting @flexiondotorg here...

**Comment by ThanosApostolou** [comment]
Yeah in manjaro the maintainer fixed it by building the **mate-desktop** over the latest snapshot. But, I asked the Antergos maintainer to update **mate-tweak** and even if I warned him for the error, he probably didn't understand it and he updated **mate-tweak** without **mate-desktop** and now it's completely broken. Then I thought that since most distributions build **mate-tweak**, it would be easier for everybody if this patch was backported into a stable point release of **mate-desktop** instead of trying to ask each maintainer to build mate-desktop over a git snapshot.

**Comment by ThanosApostolou** [comment]
Just tested OpenSuse Tumbleweed and mate-tweak is broken there too. So, this is really needed all mate-tweak will break soon or later on all rolling distros (I don't know what's the current condition on Solus but I think it doesn't have the latest mate-tweak yet).

**Comment by flexiondotorg** [comment]
Now that MATE Desktop 1.20 is released this issue can be closed.
