### ISSUE TITLE
Statically linked binaries

### ISSUE THREAD

**Issue by djmattyg007** [mate-desktop/mate-desktop#273]
How would I go about creating a statically linked binary for mate-terminal for personal use?

**Comment by raveit65** [comment]
Please use the template!
Sorry, we don't work on reports any more without using the template.
Try again.

**Comment by djmattyg007** [comment]
What I'm asking isn't really an issue, more just a question. It doesn't really fit into the outline provuded by the template. Is there somewhere better I should be asking this question?
