### ISSUE TITLE
"Install Ubuntu MATE 17.10" does not install when the live system is on the same external drive

### ISSUE THREAD

**Issue by fiedl** [mate-desktop/mate-desktop#278]
I'm trying to install the current alpha 2 onto an external ssd. But I'm running into issues, probably because I've `dd`ed the live system onto a small partition on the same drive. Usually this is way faster for me than using a separate usb stick, but the installer doesn't like it.

#### Expected behaviour

When installing mate to an already formatted ext4 partition on an external ssd drive while the mate live system is on another partition on the same drive, mate is installed on the specified partition.

#### Actual behaviour

When installing mate to an already formatted ext4 partition on an external ssd drive while the mate live system is on another partition on the same drive, the installer first tells correctly that there are no changes to the partitions, but then complains that it needs to change the partitions and thus needs to unmount all partitions on that drive. This fails, because the live system is on the same drive.

I guess, the installer tries to unmount everything on the drive it will install mate to.

I'm sorry that I didn't copy the exact wording of the error message. If it helps, I could reproduce it and paste the wording here.

#### Steps to reproduce the behaviour

1. Connect an external ssd and create several partitions, including an ext4 partition on which mate will be installed, and a small partition. `dd` the mate iso onto the small partition.
1. Boot from the small partition on the external drive, which is the mate live system.
1. Start "Install Ubuntu MATE 17.10"
1. Choose the ext4 partition in the external drive to be the root (`/`) partition, but don't mark it for formatting. It's already formatted.
1. Start the installation process.
1. The installer says (correctly) that there are no changes needed to the drive.
1. The installer says (incorrectly) that it needs to make changes to the drive and thus needs to unmount everything on the drive.

The system won't be installed.

#### MATE general version

MATE Desktop Environment 1.18.0

#### Package version

```
ubuntu-mate@ubuntu-mate:~$ ubiquity --version
17.10.1
```

**Comment by flexiondotorg** [comment]
You need to raise your bug against Ubiquity, the issue you're describing is not related to upstream MATE ☺️

 * https://bugs.launchpad.net/ubiquity

**Comment by fiedl** [comment]
Yeah, thanks.

I head on linux unplugged that you've moved the repos to github and I thought, now it's easy to drop by and file a bug :)
