### ISSUE TITLE
MATE desktop settings do not survive a reboot. 

### ISSUE THREAD

**Issue by pipy** [mate-desktop/mate-desktop#280]
#### Expected behaviour
Changing a theme or any other desktop setting change will persist after a reboot. 

#### Actual behaviour
All settings are reset to default after a reboot. (Also background image cannot at all be changed.. on clicking on different backgrounds nothing happens)

#### Steps to reproduce the behaviour
Start with the basic lubuntu 17.04 setup, then install packages ubuntu-mate-core & ubuntu-mate-desktop. Change desktop settings(like the theme) and restart the computer.

#### MATE general version
MATE 1.18

#### Linux Distribution
lubuntu 17.04 (zesty)

**Comment by monsta** [comment]
We can't solve distro-specific issues. Please report it against [ubuntu-mate-meta source package](https://launchpad.net/ubuntu/+source/ubuntu-mate-meta/+bugs).
