### ISSUE TITLE
Fresh MATE install on RHEL 7.4 yields numerous display issues

### ISSUE THREAD

**Issue by jtrutwin** [mate-desktop/mate-desktop#284]
#### Expected behaviour

The same behavior as that when installing with RHEL 7.3, things look nice.

#### Actual behaviour

When installing MATE via EPEL using a standard RHEL 7.4 (and presumably CentOS 7.4) install many applications in MATE do not display correctly.  Scrollbars are missing from terminal for example, menu text is smashed together, highlighted text is not highlighted.  I'll attach a screen image to the case, or you can view it here:  http://i.imgur.com/gjhbweM.png

The applications still function normally, e.g. even though there is no scrollbar the scrolling can still be accomplished via mouse.  The menu text still works to open menus.

#### Steps to reproduce the behaviour

Install RHEL or CentOS 7.4 (I used RHEL workstation) - install EPEL repo then groupinstall MATE as described on your install page. Open MATE terminal, scrollbars are missing, menu text is smashed together, other display issues.

#### MATE general version

1.16

I also tried updating to 1.18 from https://copr.fedorainfracloud.org/coprs/raveit65/Mate-GTK3/ but the behavior is the same.  It appears something in gnome/gtk between RHEL 7.3 and 7.4 changed.  From RHEL release notes: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html-single/7.4_Release_Notes/index.html#new_features_desktop it appears there were major changes in gnome and GTK as these issues are not present in RHEL 7.3.

#### Package version

mate-desktop-1.16..2-1.el7.x86_64

#### Linux Distribution

RHEL 7.4 Workstation x86_64

#### Link to downstream report of your Distribution

I filed a case with red hat but they said MATE is unsupported and to file a case with you.

**Comment by jtrutwin** [comment]
![gjhbwem](https://user-images.githubusercontent.com/1328349/29420283-23cf8dcc-8337-11e7-8447-c0db0b07878a.png)

Image of what MATE terminal looks like in RHEL 7.4

**Comment by raveit65** [comment]
What do you expect if you switch your sytem from gtk+-3.14 to gtk+3.22  :P 
You need to update mate-themes to mate-themes-3.22.13-1.el7 from epel-testing. and all will be good.
I am just waiting for Centos7.4 update as most ppl use cetos7, than i will pushh this update to stable.
Pushing this before centos has updated will be a mess for their users.
Rhel7 and Oracle Linux 7.4 users can use epel-testing repo for the moment.

Closing this as it is more 'why do rhel7 devs update gtk+ during release cycle' issue.
I am fedora maintainer but i would never do such things ;-)

**Comment by jtrutwin** [comment]
Believe me, I left a snarky response on my RHEL case - this is silly.  Thanks for your quick response raveit65, also does your 1.18 build work with 7.4?  Gonna try your suggestion now.

**Comment by raveit65** [comment]
Yes, the 1.18 works fine here, but it's gtk3+.
Switching to MATE-1.18 means to switch MATE desktop to gtk3 as 1.16 was the last release with gtk3 and gtk2 bits.
I expect that most rhel7/centos7 users don't want such a hard step during release cycle.
And believe me we have a few issues with Mate on gtk3 open.
It depends on your use case if you will be affect by such an open issue.
Maybe you're are lucky or not.
For this reasons i don't want update epel7 repo to 1.18.
If people want to use latest 1.18 they can use my corps repo, packages are rebuild from fedora 26 there.

**Comment by jtrutwin** [comment]
A HUGE thank you raveit65 - I can confirm that worked.  Thank you thank you thank you - now I don't have to try to back my lab image back to 7.3.

**Comment by jtrutwin** [comment]
For now I'm sticking with 1.16 - I image our lab computers here at the university I work at with RHEL7 and I'll wait a bit before making that jump - it just has to work.  I'd prefer to use gnome3 but surprising (or maybe unsurprisingly) most of the CSCI/Physics/Math majors and faculty don't like it at all.

**Comment by monsta** [comment]
For reference, here's a list of our apps that are already GTK+3 in 1.16:
- engrampa
- mate-notification-daemon
- mate-polkit
- mate-session-manager
- mate-system-monitor (since 1.14)
- mate-terminal
- mozo (since 1.14)

These apps suffered from GTK+3 update from 3.14 to 3.22, mostly because of internal theming changes in GTK+...

All other apps and libs are still GTK+2 in 1.16 by default. They can be built with GTK+3 as well if needed.
The complete migration to GTK+3 happened with 1.18.
