### ISSUE TITLE
No Middle Mouse Button

### ISSUE THREAD

**Issue by caltrop-3** [mate-desktop/mate-desktop#285]
#### Expected behaviour
middle button

#### Actual behaviour
does nothing

#### Steps to reproduce the behaviour
click middle button

#### MATE general version
18.2

#### Package version
unknown

#### Linux Distribution
Mint

#### Link to downstream report of your Distribution
none

##### additional information
even after enabling middle button it still does not work

touch-pad 2-finger emulation works as expected

Section "InputClass"
        Identifier  "Marble Mouse"
        MatchProduct "Logitech USB Trackball"
#        Identifier  "Marble Mouse"
#        MatchProduct "Logitech, Inc. Marble Mouse (4-button)"

        MatchIsPointer "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"

        Option "ButtonMapping" "3 8 1 4 5 6 7 2 2"

        Option "EmulateWheel" "true"
        Option "EmulateWheelButton" "9
        Option "EmulateWheelInertia" "20"

        Option "Emulate3Buttons" "true"
        Option "ZAxisMapping" "4 5"
#       Option "XAxisMapping" "6 7"
EndSection

**Comment by monsta** [comment]
This library doesn't handle middle button behavior.
