### ISSUE TITLE
Is StatusNotifier spec. implemented in MATE 1.8 (Mint 18.2)

### ISSUE THREAD

**Issue by oblongau** [mate-desktop/mate-desktop#286]
#### Expected behaviour
Running calibre (https://calibre-ebook.com/) as:
calibre --start-in-tray
should result in calibre starting minimized to system tray
(https://manual.calibre-ebook.com/generated/en/calibre.html)
#### Actual behaviour
calibre starts and stays open as a window. If started in a terminal, this message appears:
"Failed to create system tray icon, your desktop environment probably does not support the StatusNotifier spec"

#### Steps to reproduce the behaviour
Install calibre from calibre site.
Test by running, as normal user, in terminal:
calibre --start-in-tray 

#### MATE general version
1.18.0

#### Package version
1.18.0-1+sonya

#### Linux Distribution
Linux Mint 18.2 64 bit

**Comment by rilian-la-te** [comment]
AFAIK, yes. If not, you can use my 3rd-party applet.

**Comment by alexarnaud** [comment]
Hello,

It is implemented but it is disabled by default on Linux Mint.  You could update the "enable-sni-support" from false to true with Dconf.

Best regards.

**Comment by oblongau** [comment]
Thanks again. I installed dconf-editor, ran it to set org>mate>panel>general>enable-sni-support

But at boot time there is now a pop up:
"Notification Area" has quit unexpectedly. If you reload a panel object, it will automatically be added back to the panel."

The network connection/speaker etc. icons are then not showing. If I click "Reload" then they reappear. There is no indication there that calibre is running, but it is actually properly running in the background.
dmesg has this entry:

`notification-ar[1828]: segfault at 22 ip 00007f4382aa5268 sp 00007fff14c685b0 error 6 in libglib-2.0.so.0.4800.2[7f4382a85000+10f000]`

var/log/syslog has:

```
Sep  4 18:13:55 bob-mint org.mate.panel.applet.NotificationAreaAppletFactory[1699]: (notification-area-applet:1828): status-notifier-watcher-WARNING **: Status Notifier Item with bus name 'org.kde.StatusNotifierItem-1774-1' and object path '/StatusNotifierItem' is already registered

Sep  4 18:13:55 bob-mint org.mate.panel.applet.NotificationAreaAppletFactory[1699]: (notification-area-applet:1828): GLib-GIO-WARNING **: Received property Version with type i does not match expected type u in the expected interface

Sep  4 18:13:55 bob-mint org.mate.panel.applet.NotificationAreaAppletFactory[1699]: (notification-area-applet:1828): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -1 and height 15

Sep  4 18:13:55 bob-mint org.mate.panel.applet.NotificationAreaAppletFactory[1699]: (notification-area-applet:1828): GLib-CRITICAL **: the GVariant format string '(i@a{sv}@av)' has a type of '(ia{sv}av)' but the given value has a type of '(ia{sv}a(ia{sv}av))'

Sep  4 18:13:55 bob-mint org.mate.panel.applet.NotificationAreaAppletFactory[1699]: (notification-area-applet:1828): GLib-CRITICAL **: g_variant_get: assertion 'valid_format_string (format_string, TRUE, value)' failed

Sep  4 18:13:55 bob-mint kernel: [   35.800171] notification-ar[1828]: segfault at 22 ip 00007f4382aa5268 sp 00007fff14c685b0 error 6 in libglib-2.0.so.0.4800.2[7f4382a85000+10f000]
[...]
Sep  4 18:14:32 bob-mint org.mate.panel.applet.NotificationAreaAppletFactory[1699]: (notification-area-applet:2407): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -1 and height 15`
```
The panel size is 25 pixels, if that is a factor.

Any ideas as to what next?

**Comment by alexarnaud** [comment]
OK, could you close this bug and open another one for the segfault? We need to have all the requested data to help you (the bug template).

It shouldn't be segfault.

Best regards.

**Comment by oblongau** [comment]
Hopefully this is what you mean:
https://github.com/mate-desktop/mate-desktop/issues/288
