### ISSUE TITLE
Where is a MATE 1.20 roadmap?

### ISSUE THREAD

**Issue by Sunderland93** [mate-desktop/mate-desktop#287]
1.18 still here http://wiki.mate-desktop.org/roadmap

**Comment by raveit65** [comment]
Like 'Talking Heads' said,
we on the road to nowhere .... :-)

**Comment by raveit65** [comment]
Like 'Talking Heads' said, we are on the road to nowhere.... :-)

**Comment by Sunderland93** [comment]
Sadly...

**Comment by ulgrimar** [comment]
Still no Roadmap for 1.20. I would recommend:  Add support for Wayland, Add support for HiDPI and as Feature "[Better View for Embleme](https://github.com/mate-desktop/caja/issues/341)"  🥇

**Comment by monsta** [comment]
Roadmap is updated for 1.20 and 1.22
