### ISSUE TITLE
SEGFAULT when StatusNotifier is Used.

### ISSUE THREAD

**Issue by oblongau** [mate-desktop/mate-desktop#288]
#### Expected behaviour
No segfault. Notification area to be updated, presumably to show calibre icon.

#### Actual behaviour
Popup saying, "Notification Area" has quit unexpectedly. If you reload a panel object, it will automatically be added back to the panel."
The network connection/speaker etc. icons are then not showing. If I click "Reload" then they reappear. There is no indication there that calibre is running, but it is actually properly running in the background.

dmesg has this entry:

`notification-ar[1828]: segfault at 22 ip 00007f4382aa5268 sp 00007fff14c685b0 error 6 in libglib-2.0.so.0.4800.2[7f4382a85000+10f000]`

var/log/syslog has:

```
Sep  4 18:13:55 bob-mint org.mate.panel.applet.NotificationAreaAppletFactory[1699]: (notification-area-applet:1828): status-notifier-watcher-WARNING **: Status Notifier Item with bus name 'org.kde.StatusNotifierItem-1774-1' and object path '/StatusNotifierItem' is already registered

Sep  4 18:13:55 bob-mint org.mate.panel.applet.NotificationAreaAppletFactory[1699]: (notification-area-applet:1828): GLib-GIO-WARNING **: Received property Version with type i does not match expected type u in the expected interface

Sep  4 18:13:55 bob-mint org.mate.panel.applet.NotificationAreaAppletFactory[1699]: (notification-area-applet:1828): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -1 and height 15

Sep  4 18:13:55 bob-mint org.mate.panel.applet.NotificationAreaAppletFactory[1699]: (notification-area-applet:1828): GLib-CRITICAL **: the GVariant format string '(i@a{sv}@av)' has a type of '(ia{sv}av)' but the given value has a type of '(ia{sv}a(ia{sv}av))'

Sep  4 18:13:55 bob-mint org.mate.panel.applet.NotificationAreaAppletFactory[1699]: (notification-area-applet:1828): GLib-CRITICAL **: g_variant_get: assertion 'valid_format_string (format_string, TRUE, value)' failed

Sep  4 18:13:55 bob-mint kernel: [   35.800171] notification-ar[1828]: segfault at 22 ip 00007f4382aa5268 sp 00007fff14c685b0 error 6 in libglib-2.0.so.0.4800.2[7f4382a85000+10f000]
[...]
Sep  4 18:14:32 bob-mint org.mate.panel.applet.NotificationAreaAppletFactory[1699]: (notification-area-applet:2407): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -1 and height 15`
```

#### Steps to reproduce the behaviour
Using dconf-editor, set org>mate>panel>general>enable-sni-support

This fault occurs when trying to run calibre to start minimized to system tray.
(https://manual.calibre-ebook.com/generated/en/calibre.html)

In Control Centre|Startup Applications "calibre --start-in-tray" is the command.

Or, with calibre not running in background, running "calibre --start-in-tray" results in the same error and behaviour.

#### MATE general version
1.18.0

#### Package version
1.18.0-1+sonya

#### Linux Distribution
Linux Mint 18.2 64 bit

**Comment by monsta** [comment]
Try upgrading your system, the latest mate-panel in this Mint is 1.18.3-2+sonya.

**Comment by monsta** [comment]
Anyway, that applet is a part of [mate-panel](https://github.com/mate-desktop/mate-panel). File a new report there if the problem still happens with the latest version.
