### ISSUE TITLE
Keyboard shortcuts for "Move window to * of screen" not working for some software

### ISSUE THREAD

**Issue by guillaumecharbonnier** [mate-desktop/mate-desktop#290]
#### Expected behaviour
Using actions from "Keyboard Shortcuts" like "Move window to * of screen" to move windows from one screen to another one.

#### Actual behaviour
It works perfectly for most software (tested: caja, mate terminal) but does not work for Firefox and Thunderbird. Instead their windows move to the desired screen when shortcut keys are pressed but they turn back to original position when keys are released.

#### Steps to reproduce the behaviour
Set up multiple displays in extended mode.
Set shortcuts for "Move window to * of screen" in "Keyboard Shortcuts".
Open Firefox/Thunderbird.
Use shortcut to try to move the window from one display to another one.

#### MATE general version
1.12.1

#### Linux Distribution
Ubuntu 16.04 LTS

**Comment by monsta** [comment]
> Instead their windows move to the desired screen when shortcut keys are pressed but they turn back to original position when keys are released.

It's a part of more general issue, https://github.com/mate-desktop/marco/issues/28
