### ISSUE TITLE
Why has not MATE 1.19 been released on the site and why are all MATE packages on Arch Linux still in version 1.18 or lower?

### ISSUE THREAD

**Issue by xitero** [mate-desktop/mate-desktop#294]
I use MATE in Arch Linux and I have been following the site to see if there are new updates, as I did not see anything I thought MATE was dead since March of that year. I looked for github and saw here that the work continues, so my question is, why are MATE packages in Arch Linux still in version 1.18 instead of 1.19 and why has version 1.19 not been announced in the official site news?

To find out what I'm talking about, check out the package versions here:
https://www.archlinux.org/packages/?sort=&q=mate-&maintainer=&flagged=
https://www.archlinux.org/groups/x86_64/mate-extra/

Thanks in advance.

**Comment by flexiondotorg** [comment]
MATE 1.19 releases are development snapshots, for those who want to test ahead of what will become MATE 1.20.

The MATE team also have no influence over what versions of MATE distro package and ship, so questions such as this should be sent to the appropriate downstream projects ☺️

**Comment by raveit65** [comment]
We are not responsible for packaging MATE in distros. Please file out a report at ArchLinux bugreporting tool as ask Archlinux for updating MATE.
