### ISSUE TITLE
mateconftool-2 is missing

### ISSUE THREAD

**Issue by elypter** [mate-desktop/mate-desktop#295]
it is not present on my installation and although it is mentioned on several sites on the net it is neither in any of the default repositories, on a separate homepage, this github account or anywhere else on the internet, almost like it has been purged from history. i need it as it is the only way to toggle Mint-X with Mint-Y as a cheap night mode. is this intentional? and if so, is there any secret place to still obtain this mysterious tool from?

**Comment by monsta** [comment]
MateConf had been replaced with GSettings in 2013

http://mate-desktop.org/blog/2013-04-02-mate-1-6-released/
