### ISSUE TITLE
org.mate.interface can-change-accels gschema key doesn't work

### ISSUE THREAD

**Issue by tarakbumba** [mate-desktop/mate-desktop#296]
#### Expected behaviour
Accels can be modified when org.mate.interface can-change-accels is set true.

#### Actual behaviour
After migrating to GTK+3 enabling can-change-accels key doesn't work and a user can not change an accel mouse over.

#### Steps to reproduce the behaviour
1. Set org.mate.interface can-change-accels to true
2. Open a mate component like caja, mouse over on a setting say, Appearance > Show Hidden File option and try to change default value.

#### MATE general version
mate-1.18.0 and up

#### Package version
mate-desktop-1.19.2

#### Linux Distribution
Mageia

**Comment by monsta** [comment]
It won't work with GTK+3, see [here](https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-can-change-accels). We should just remove this option.

**Comment by tarakbumba** [comment]
Yes, you're right. This option should be dropped then. It was nice to configure accels tough.

**Comment by monsta** [comment]
It was nice, though it sometimes could lead to some confusion 🙂 

https://ubuntu-mate.community/t/in-caja-pressing-y-key-opens-new-tab-cant-rename-files/13551

**Comment by akshaypuradkar** [comment]
so how do i change the accels?
