### ISSUE TITLE
Move between windows of an application

### ISSUE THREAD

**Issue by curious-jim** [mate-desktop/mate-desktop#303]
#### Expected behaviour
There are 2 hotkeys to switch between windows of the same app by default: `Alt+~` and `Alt+F6`. One with popup, another instant.

#### Actual behaviour
It works only with some apps, for example Firefox or Sublime Text. But when I need it the most, in JetBrains IDE, Chromium, TortoiseHg, it doesn't work. App border blinks and that's it.

#### Steps to reproduce the behaviour
press `Alt+~` with opened two or more windows of JetBrains IDE, Chromium, TortoiseHg

#### MATE general version
1.19.3

#### Linux Distribution
Fedora 27

**Comment by raveit65** [comment]
Confirmed that using `Alt+F6` doesn't work with  Chromium in f26 with MATE from master branch, the other apps i don't use.
But you can use alt-tab for switching between 2 Chromium windows as workarround, or not?
No idea how to test `Alt+~` with my keyboard layout.
For `~` i need to press `AltGr`.

**Comment by curious-jim** [comment]
`Alt+Tab` works, but it's not exactly the same. And `~` is the same button as ` (tilde) on my keyboard, I just couldn't wrap it in `code`

**Comment by raveit65** [comment]
At least i think mate-desktop package is the wrong repo, but i am not sure if it is marco WM or libmate-keyboard related.

**Comment by curious-jim** [comment]
sorry, I couldn't really find where to post it. Is there a way to move it where it should be?

**Comment by monsta** [comment]
Both keybindings are from Marco. It's not possible to move reports to another repo, so please file a new one for Marco.
