### ISSUE TITLE
Confusing package name scheme for mate-desktop

### ISSUE THREAD

**Issue by allo-** [mate-desktop/mate-desktop#305]
I was confused by the debian package ``mate-desktop`` not being a meta-package. I expected it to be something like ``kde-full`` (both not the same as ``-desktop-environment`` packages).

Maybe you can coordinate with the distributions to have a clearly named meta-package and possibly the name ``mate-desktop`` should refer to this or be avoided for other packages as it creates confusion if it installs the mate desktop or not.

mate-desktop could possibly be packaged as ``libmate-desktop-bin`` if I understand the description of the debian package right and it only packages some binaries belonging to libmate-desktop.

Here is the related [Debian Bug #891986](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891986)

**Comment by sunweaver** [comment]
in Debian, we see meta packages name "gnome", "xfce4", "plasma-desktop" (woo?!?), lxde, lxqt. There is no real standard way of naming meta packages.

I could agree to add a "mate" meta package on Debian, that pulls in mate-desktop-environment.

Personally, I feel that the name "mate-desktop-environment" is quite self-explanatory.

And... you are not the first person that stumbles over "mate-desktop" vs. "libmate-desktop" (which describes better what this upstream component of the MATE desktop is about.

**Comment by allo-** [comment]
I do not know how mate is packaged, but usually there is a difference between the distribution ``-desktop-environment`` package with a default desktop possibly with additional programs and some ``DESKTOP-full`` package.
I think i.e. kubuntu does not install everything in ``kde-full`` but it installs some useful other tools.

I stumbled at it, because some meta package was missing, so somewhere marco got uninstalled or was not installed after some WM change(?), leaving me with a mate desktop without window manager. So my idea was just to install the meta package to fix it. And there I got confused with the package name thinking of a broken meta package and not even considering that it's something totally unrelated.

It worksforme now and the original bugreport was closed correctly but in another mail (which got lost in the bugreport as it went to the maintainer only) I suggested to have a clear meta package for the desktop without any distribution specific tools. I would expect it to have some name like ``mate``, ``mate-desktop``, ``mate-full`` or something similar intuitive.

I am still not sure if it is an issue of packaging in the distribution or of the upstream. Renaming ``mate-desktop`` is an upstream issue but this will probably complicate a lot of things anyway. Maybe we should have an ``mate`` package.

How much are you involved in the (debian) packaging?

**Comment by flexiondotorg** [comment]
This is not an upstream issue.

**Comment by lukefromdc** [comment]
I still remember when Phoronix and others thought the release of mate-desktop 1.10 was the release of all of MATE 1.10, even though GNOME had used the same naming scheme for years

**Comment by lukefromdc** [comment]
I would suggest we keep it the same, as GNOME does. I think Debian and Ubuntu call it libmate-desktop or something along those lines anyway.

**Comment by allo-** [comment]
GNOME has here:

    libgnome-desktop-3-12   libgnome-desktop-3-17   libgnome-desktop-3-de
    gnome-desktop3-data    gnome-desktop-testing

and no ``gnome-desktop`` package at all.

MATE has it split into 

    libmate-desktop-2-17  libmate-desktop-dev   libmate-desktop-doc
    mate-desktop                     mate-desktop-environment         mate-desktop-environment-extra   
    mate-desktop-common              mate-desktop-environment-core    mate-desktop-environment-extras 
    
On Debian Buster, where libmate-desktop seems to be split into libmate-desktop-2-17 for the library and mate-desktop for the binaries.

**Comment by sunweaver** [comment]
On  Di 06 Mär 2018 22:39:23 CET, allo- wrote:

> GNOME has here:
>
>     libgnome-desktop-3-12   libgnome-desktop-3-17   libgnome-desktop-3-de
>     gnome-desktop3-data    gnome-desktop-testing
>
> and no ``gnome-desktop`` package at all.
>
> MATE has it split into
>
>     libmate-desktop-2-17  libmate-desktop-dev   libmate-desktop-doc
>     mate-desktop                     mate-desktop-environment         
>  mate-desktop-environment-extra
>     mate-desktop-common              mate-desktop-environment-core    
>  mate-desktop-environment-extras
>
> On Debian Buster, where libmate-desktop seems to be split into  
> libmate-desktop-2-17 for the library and mate-desktop for the  
> binaries.

I have amended this issue now by documentation:
https://anonscm.debian.org/cgit/pkg-mate/mate-desktop.git/commit/?id=baa169272d7ed5b97590988177b2f79831369bcb

Project and package renames are a big hassle with no valuable outcome  
in this case.

Please let's fade out this discussion...

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by alexarnaud** [comment]
Le 07/03/2018 à 06:48, Mike Gabriel a écrit :
> I have amended this issue now by documentation:
> https://anonscm.debian.org/cgit/pkg-mate/mate-desktop.git/commit/?id=baa169272d7ed5b97590988177b2f79831369bcb

Thank you Mike for your proposal, it's a great compromise.

Best regards,
Alex.
