### ISSUE TITLE
mate-color-select: select color from first argument, feature request

### ISSUE THREAD

**Issue by TomaszGasior** [mate-desktop/mate-desktop#307]
#### Expected behaviour
When I execute `mate-color-select #FF00FF` color `#FF00FF` should be selected automatically.

#### Actual behaviour
`mate-color-select` doesn't use arguments. Even don't have `--help`. ;(

#### Package version
mate-desktop 1.20.0-1

#### Linux Distribution
Arch Linux fully updated

**Comment by flexiondotorg** [comment]
If you already know the colour, what is the use case for passing a a colour to a colour picker from the command line?

**Comment by TomaszGasior** [comment]
I thought about something like that:
https://github.com/mate-desktop/mate-desktop/issues/252
Sorry for duplicate.
