### ISSUE TITLE
Appearance Preferences: "Get more backgrounds" link -- Broken?

### ISSUE THREAD

**Issue by nissimnanach** [mate-desktop/mate-desktop#311]
#### Expected behaviour
Click link, get more backgrounds.

#### Actual behaviour
Link leads to
http://mate-desktop.org/backgrounds/
which just has a link to
http://gnome-look.org/index.php?xcontentmode=170x171x172x173x174x175x176x177x178x179
which says "You have no authorization for this page."

Only contact on mate-desktop.org is webmaster@[same] which returned to me "554: 5.7.1 Service unavailable"
#### Steps to reproduce the behaviour
click link.

#### MATE general version
Linuxmint 17.3

**Comment by vkareh** [comment]
@nissimnanach - I've submitted a pull request to fix these links: mate-desktop/mate-desktop.org/pull/93 

gnome-look.org (which belongs to opendesktop.org) now also has mate-look.org. Here's where the backgrounds are: https://www.mate-look.org/browse/cat/359

Also, I couldn't find the contact link to webmaster - where are you looking for that?

**Comment by nissimnanach** [comment]
@vkareh - On the page
: http://mate-desktop.org/backgrounds/
The hypertext to 
: "Contents © 2018 The MATE Team" 
is 
: webmaster@mate-desktop.org
