### ISSUE TITLE
HiDPI, blurry icons

### ISSUE THREAD

**Issue by Safari77** [mate-desktop/mate-desktop#314]
#### Expected behaviour
I heard mate 1.20 has HiDPI support, but it seems to use very small versions of the icons.

#### Actual behaviour
I used display to load 256x256 and 48x48 images of the icons at
```/usr/share/icons/Adwaita/*/apps/preferences-desktop-theme.png```, shown at 100% size along with mate-panel
![blurry-appearance](https://user-images.githubusercontent.com/3876865/39251475-0d754130-48ac-11e8-9efb-ee8f8402a5c6.png)

#### Steps to reproduce the behaviour
```org.mate.interface window-scaling-factor 2```
3840 x 2160 display

#### MATE general version
1.20

#### Linux Distribution
Fedora 27

**Comment by lukefromdc** [comment]
Cpufreq applet looks just fine with the existing icons as merged
![cpufreq_applet](https://user-images.githubusercontent.com/14036792/39961463-7579cebc-5604-11e8-9b87-326f73d06205.png)

**Comment by MartinX3** [comment]
2560x1440
Linux Mint x64 19 Beta with Mate Desktop and latest updates.
Still blurry.

![grafik](https://user-images.githubusercontent.com/4518092/41498258-51260212-7169-11e8-973a-3d7fb2a25246.png)

**Comment by raveit65** [comment]
I am in doubt that you're using latest mate-panel release in your distro, icons of panel-launcher are fixed.

**Comment by MartinX3** [comment]
@raveit65 
I'm using version 1.20.1-3ubuntu1
Next update will fix that bug?

**Comment by MartinX3** [comment]
I will try that, thank you!
