### ISSUE TITLE
laptop sleeps if lid closed when external monitor is connected

### ISSUE THREAD

**Issue by philthynz** [mate-desktop/mate-desktop#318]
#### Expected behaviour
Laptop should not sleep if you close the laptop lid and there is an external display detected. The laptop display should only deactivate.

#### Actual behaviour
Laptop sleeps

#### Steps to reproduce the behaviour
Plug in monitor, close lid

#### MATE general version
1.20

#### Linux Distribution
Ubuntu Mate

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu-mate/+bug/1772328

**Comment by raveit65** [comment]
This is normal behaviour and not a error.
What do you expect if those keys are set to suspend.
```
[rave@satellite ~]$ gsettings get org.mate.power-manager button-lid-ac
'suspend'
[rave@satellite ~]$ gsettings get org.mate.power-manager button-lid-battery
'suspend'
```
I use this with an external monitor
```
[rave@satellite ~]$ gsettings get org.mate.power-manager button-lid-ac
'nothing'
```
You can do the same with battery setting.

**Comment by philthynz** [comment]
I would not call it an error or bug. It's more of a feature request. Ubuntu, XUbuntu and Kubuntu have all implemented '/org/gnome/settings-daemon/plugins/power/' 'lid-close-suspend-with-external-monitor'. The laptop should not sleep if an external display is connected. It should be able to sleep if it's connected to AC (without external monitor) and on battery when closing the lid. It's a very useful feature in other desktops. For example, when using a docking station. People just want to dock, and then close the lid without having to configure anything with XRandR. Can this feature be carried over to '/org/mate/power-manager/'? It's a very good use case.

**Comment by raveit65** [comment]
I  think this is the wrong project. As org.mate.power-manager.gschema.xml if from mate-power-manger.
Sorry, we can't move reports here.

**Comment by philthynz** [comment]
That's fine. This issue can be closed and I will reference it there
