### ISSUE TITLE
Need more useful API

### ISSUE THREAD

**Issue by yetist** [mate-desktop/mate-desktop#319]
Can the new API in gnome-desktop be implemented in mate-desktop? For example, like the following:
```
char *        gnome_get_language_from_locale    (const char *locale,
                                                 const char *translation);
char *        gnome_get_country_from_locale     (const char *locale,
                                                 const char *translation);
char **       gnome_get_all_locales             (void);
gboolean      gnome_parse_locale                (const char *locale,
                                                 char      **language_codep,
                                                 char      **country_codep,
                                                 char      **codesetp,
                                                 char      **modifierp);
char *        gnome_normalize_locale            (const char *locale);
gboolean      gnome_language_has_translations   (const char *code);
char *        gnome_get_language_from_code      (const char *code,
                                                 const char *translation);
char *        gnome_get_country_from_code       (const char *code,
                                                 const char *translation);
gboolean      gnome_get_input_source_from_locale (const char  *locale,
                                                  const char **type,
                                                  const char **id);
```

**Comment by raveit65** [comment]
Why not.......... for what do you needed?
Looks like an tool for language and localization.

**Comment by yetist** [comment]
Want to write a user-manage tool for mate-control-center, it need some api for user language choose.

**Comment by raveit65** [comment]
Great idea, a tool for switching the language is really missing since i switch fedora to use slick-greater instead of lightdm-gtk.
Lightdm-gtk offers an option to switch session language but slickgreeter doesn't.
So i agree with adding those API.
@monsta @lukefromdc @sc0w @vkareh 
Thoughts?

**Comment by lukefromdc** [comment]
I don't know much about working with languages (I only speak one and purge unused locales), but this strikes me as a missing part of slick-greeter if DE's now expect it in the session greeter. If nothing else, it could make the greeter useless on a machine used by two different people who don't speak any common language between them

No problem with adding this to MATE to deal with the reality of possible randomly sourced greeters, but I am not in a good position to test it.

**Comment by raveit65** [comment]
A language tool is also useful for posting screenshots/logs here in one language which everybody understand ;)

**Comment by flexiondotorg** [comment]
I think improving the options for switching session locales is good :smiley: 

What I'd like to see is a fork of mate-desktop with the required API changes implemented in a branch and the proposed tool for switching locales in another repo so we can better review both. 

@yetist  Are you going to keep the `gnome_` prefixes on function names or will you be changing them to `mate_`?

**Comment by monsta** [comment]
Hmm, language switch tool... should it be dependent on certain DE? Aren't there any cross-desktop tools?

**Comment by raveit65** [comment]
> Aren't there any cross-desktop tools?

No, before fedora switched to use slick-greeter because of HIDPI support it was possible to switch the **session** language with lightdm-gtk, but slick-greeter doesn't have this option.
In result it is impossible to switch the language after installation.

**Comment by lukefromdc** [comment]
It would seem to me that that calls for a bug report against slick-greeter. I do not know if it is possible to change something like this in a running session or not.

**Comment by lukefromdc** [comment]
Well, a feature request. From what you say, if you want to change the language in Fedora you must either reinstall, add another greeter and switch to it, or possibly edit files manually (no idea how here)

**Comment by monsta** [comment]
I see the problem with the greeter, but I meant some tools that allow switching language from the running session of any DE.

For example, Mint has [mintlocale](https://github.com/linuxmint/mintlocale/).

**Comment by monsta** [comment]
As for the feature request, this one looks relevant: https://github.com/linuxmint/slick-greeter/issues/77

**Comment by raveit65** [comment]
I know what you mean, but there in no tool like this in redhat-country and there derivatives.
Otherwise i wouldn't say that it is needed since several post.
Why not thinking a bit positive if someone wants to modernize MATE?

**Comment by lukefromdc** [comment]
It just seemd to me that a session manager with no ability to change/reset the language would mean that unless every DC included their own tool, there would be some DE's for which you'd have to add another DE, add another greeter, or reinstall to change the language. 

If this has gotten to be a patchwork though, it may make sense for both DE's and greeters to include such tools, so as to minimize the number of combinations where a default install does not allow changing the language from a gui.

**Comment by raveit65** [comment]
@yetist 
Any progress with your tool for mat-control-center?
I am happy to test it.

**Comment by yetist** [comment]
@raveit65 
My colleague wrote a user management tool, but it is not perfect at the moment.
https://github.com/zhuyaliang/user-admin

**Comment by raveit65** [comment]
@yetist 
```
meson.build:92:0: ERROR:  Native dependency 'gnome-desktop-3.0' not found
```
So it's for gnome at the moment?
I am a bit in worry to test language switching, because i see only English and Chinese in dropdown menu.

Btw. in the past i forked gnome-accountsdialog (before they switched it to a control-center only applitcation`.
Sadly i wasn't able to port to gtk3, so i gave up to maintain it.
https://github.com/raveit65/mate-accountsdialog

**Comment by raveit65** [comment]
Switching to english works well, and i was able to reset to my language with another tool.
