### ISSUE TITLE
Compiz breaks window borders

### ISSUE THREAD

**Issue by FrancescoBorzi** [mate-desktop/mate-desktop#32]
Tested on:
- Ubuntu 12.10 using Mate 1.4
- LinuxMint 13 using Mate 1.2

Using Compiz in both these distros, it simply breaks all window borders. I'm unable to use Compiz on Mate

**Comment by samcorbin** [comment]
I had this issue on MATE 1.18 on Ubuntu MATE 17.10 which leads me to this thread. I resolve it by installing `compiz-mate` through `sudo apt install compiz-mate`, logout and login. To configure Compiz, install `compizconfig-settings-manager` through `sudo apt install compizconfig-settings-manager`.
