### ISSUE TITLE
Location 

### ISSUE THREAD

**Issue by reno-a** [mate-desktop/mate-desktop#321]
Hello,

Location for weather: I do not know if it's related to the weather with "libmateweather", but many cities are not repertoried (test for french cities).
If big cities are found, other (yet important) not. Howeve, towns easy to find for others desktop-environment (like Xfce, GNOME).

To read other remarks on the Net, it seems that even indicating geographical coordinates it does not work (but I don't try it).

[same issues as https://github.com/mate-desktop/libmateweather/issues/59#issue-328969288]

#### MATE general version
1.16 & 1.20

#### Linux Distribution
Debian Stable & Sid
Fedora 28

**Comment by lukefromdc** [comment]
All of these are in libmateweather, not mate-desktop. Thus only https://github.com/mate-desktop/libmateweather/issues/59 is needed .Closing this one.
