### ISSUE TITLE
Keyboard shortcuts: SHIFT+ALT+whatever doesn't register

### ISSUE THREAD

**Issue by luispabon** [mate-desktop/mate-desktop#322]
#### Expected behaviour
When creating keyboard shortcuts, I expect to be able to make new ones with SHIFT+ALT+something.

#### Actual behaviour
Only ALT or SHIFT are registered (whichever of those keys you pressed first). This happens when registering keyboard shortcuts on the control centre, but also on third party apps like Jetbrains IDEs (which is very aggravating as I have quite a bunch of SHIFT+ALT+something).

These work fine on other DEs like Unity or Gnome on the same hardware and OS installation.

#### Steps to reproduce the behaviour
Control centre > Keyboard shortcuts > add new
Choose some name and app to launch, then try to assign SHIFT+ALT+F for instance. Only ALT+F will be registered.

#### MATE general version
1.20

#### Linux Distribution
Ubuntu bionic

**Comment by GDGooD** [comment]
Not reproduced with 1.26.1.
Succesfuly created a new shortcut with Shift+Alt+F for `pluma`.
