### ISSUE TITLE
Alt-Tab does not work when a file / folder is dragged

### ISSUE THREAD

**Issue by CreamyCookie** [mate-desktop/mate-desktop#327]
#### Expected behaviour
It should work when dragging a file.

#### Actual behaviour
Pressing <kbd>Alt</kbd> + <kbd>Tab</kbd> has no effect, when you click on a file and start to drag it. (For example, to add it as mail attachment.)

#### MATE general version
The latest from Ubuntu Mate 18.04 (up to date): 1.20.1

I'm using compiz.

#### Linux Distribution
Ubuntu Mate 18.04

**Comment by alexarnaud** [comment]
@CreamyCookie Thank you for filling us this issue.

As I can read, if the issue comes from Compiz it's not maintained by the Mate team so we couldn't do anything for you.

Could you check if you reproduce the same issue with Marco?

Best regards,
Alex.

**Comment by CreamyCookie** [comment]
@alexarnaud No problem! Yeah, sadly that seems to be a compiz specific issue. Weirdly though, there was a bug report that was fixed on this issue: https://bugs.launchpad.net/ubuntu/+source/metacity/+bug/111939

Could this not also be an issue in how Mate configures compiz?

**Comment by CreamyCookie** [comment]
Oops, this is the one about compiz: https://bugs.launchpad.net/ubuntu/+source/compiz/+bug/624810

However it was declared a duplicate of the one I linked above, so could be that it either was never fixed or it really never was a bug in compiz.

**Comment by raveit65** [comment]
Can this be closed if it is a compiz problem?

**Comment by CreamyCookie** [comment]
@raveit65 Couldn't this not also be an issue in how Mate configures / runs compiz? IIRC Ubuntu Unity uses compiz and there I never had problem with alt-tab and drag & drop.

**Comment by CreamyCookie** [comment]
@raveit65 By downstream report you mean a report the the Ubuntu Mate devs, so the following, right?  https://bugs.launchpad.net/ubuntu-mate

**Comment by alexarnaud** [comment]
Le 30/06/2018 à 10:27, raveit65 a écrit :
> I am fedora maintainer and i don't know exactly how MATE is build in ubuntu.
> There is a reason why we ask for a downstream report in our report template.
> Than you could ask this question to ubuntu maintainer ;)
> 
After reading the thread it hasn't been fixed on Compiz yet so it's a 
Compiz-related issue.

I've added a comment here: 
https://bugs.launchpad.net/ubuntu/+source/metacity/+bug/111939/comments/51

You can close this one.

Best regards,
Alex.

**Comment by CreamyCookie** [comment]
@alexarnaud Thank you!
