### ISSUE TITLE
mate user-admin

### ISSUE THREAD

**Issue by zhuyaliang** [mate-desktop/mate-desktop#329]
mate-desktop whether user management tools are needed？I wrote a user management tool, but it is not perfect at the moment.Can manage users effectively.For example : change password, change name, change language, change user type。
https://github.com/zhuyaliang/user-admin

**Comment by raveit65** [comment]
Nice, i did already test it some days ago and i plan to use it for Mate-Compiz spin from fedora, when it is ready.
I got some build warnings:
```
ninja: Entering directory `build'
[8/10] Compiling C object 'src/src@@user-admin@exe/user-password.c.o'.
../src/user-password.c: In function 'CheckInputOldPass':
../src/user-password.c:291:27: warning: implicit declaration of function 'crypt'; did you mean 'chroot'? [-Wimplicit-function-declaration]
     if(strcmp(sp->sp_pwdp,crypt(PassWord,salt)) == 0)
                           ^~~~~
                           chroot
../src/user-password.c:291:27: warning: nested extern declaration of 'crypt' [-Wnested-externs]
../src/user-password.c:291:27: warning: passing argument 2 of 'strcmp' makes pointer from integer without a cast [-Wint-conversion]
     if(strcmp(sp->sp_pwdp,crypt(PassWord,salt)) == 0)
                           ^~~~~~~~~~~~~~~~~~~~
In file included from ../src/user-password.c:4:
/usr/include/string.h:136:50: note: expected 'const char *' but argument is of type 'int'
 extern int strcmp (const char *__s1, const char *__s2)
                                      ~~~~~~~~~~~~^~~~
[10/10] Linking target src/user-admin.
```
But why i see only English and Chinese language in dropdown menu?
My native language (German) is still ignored.

**Comment by zhuyaliang** [comment]
@raveit65 I modified the language switch code.Switching based on local support language.Using the functions provided by the mate-languages.c and mate-languages.h. 
https://github.com/zhuyaliang/user-admin

**Comment by raveit65** [comment]
Cool, all local available languages are there.
And i can happily switch them.
Is there a chance to get them sorted in dropdown-menu ?

**Comment by raveit65** [comment]
For some reasons it shows the same language for all accounts (tested with 3), but login to the account shows the real previous selected language.
And i can start user-admin only from the user-session where i have it installed.
i get an error message 'can't create pid' or something like that.
But maybe this is a local problem here.

**Comment by zhuyaliang** [comment]
@raveit65 What DM（display manager） do you use?

**Comment by zhuyaliang** [comment]
The emergence of "can't create PID" is due to the reason for the permissions.I fixed this problem and sorted the language in the drop-down menu.

**Comment by raveit65** [comment]
I am using lightdm with slick-greeter as frontend.

**Comment by zhuyaliang** [comment]
”For some reasons it shows the same language for all accounts (tested with 3), but login to the account shows the real previous selected language“ I don't quite understand what you mean.Is there no effect after switching languages?

**Comment by raveit65** [comment]
Now i get a message `delete user-admin.pid in /tmp folder`, not perfect but much better, thx.

> I don't quite understand what you mean.Is there no effect after switching languages?

No, language switching works well, all accounts are using the correct language.
But the GUI doesn't show the right language for all users.
Let say:
1. user `rock` --> english (UK)
2. user `rave` --> german (DE)
![user-admin-1](https://user-images.githubusercontent.com/961604/43577256-a64536f8-964b-11e8-9369-719c376b898f.png)
![user-admin-2](https://user-images.githubusercontent.com/961604/43577257-a661e186-964b-11e8-925f-74eb2a5ed917.png)
Here the GUI shows the wrong language for user `rave`.
If i open the GUI in account of user `rave`, than he is the first user in GUI and all other accounts are shown his language.

And for some reasons the languages aren't sorted.
![user-admin-3](https://user-images.githubusercontent.com/961604/43577260-a67e5d98-964b-11e8-9b10-d79700ee35e3.png)

**Comment by zhuyaliang** [comment]
@raveit65 I'm sorry, I uploaded the wrong version of the code.This is not the expected result。I don't know why, I didn't encounter the problem you described.
![1](https://user-images.githubusercontent.com/36913152/43583119-1a09548a-9691-11e8-83e5-b376a98c9f04.png)
![2](https://user-images.githubusercontent.com/36913152/43583120-1a6d8d06-9691-11e8-9821-6dc8b41cd2f1.png)
![3](https://user-images.githubusercontent.com/36913152/43583122-1ad410bc-9691-11e8-8132-83f295349ae4.png)
I opened some output, can I help me test it?

**Comment by zhuyaliang** [comment]
@raveit65 I am very sorry, I uploaded the wrong version of the code. That is not the result I want. I don't know why I didn't reproduce the problem you described. For this reason, I opened some output deliberately. Can you test it for me?
![1](https://user-images.githubusercontent.com/36913152/43586636-b7742d4a-969a-11e8-89e2-834f5a51a7d1.png)
![2](https://user-images.githubusercontent.com/36913152/43586638-b7d9cf4c-969a-11e8-98c6-a59ebbe50b07.png)
![3](https://user-images.githubusercontent.com/36913152/43586645-b925f3b2-969a-11e8-9f18-1e0632b837be.png)

**Comment by raveit65** [comment]
@zhuyaliang 
With latest changes user-admin doesn't start any more.
```
[rave@mother user-admin]$ git pull
remote: Counting objects: 13, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 13 (delta 11), reused 13 (delta 11), pack-reused 0
Entpacke Objekte: 100% (13/13), Fertig.
Von github.com:zhuyaliang/user-admin
   af3b07b..335668a  master     -> origin/master
Aktualisiere af3b07b..335668a
Fast-forward
 src/main.c           |   83 ++++---
 src/mate-languages.c | 1299 ---------------------------------------------------------------------------------------------------
 src/mate-languages.h |   51 ----
 src/user-admin.c     |    2 +-
 src/user-base.c      |    2 +-
 src/user-info.c      |    5 +-
 src/user-share.c     |    2 +-
 src/user.h           |    4 +-
 8 files changed, 56 insertions(+), 1392 deletions(-)
 delete mode 100644 src/mate-languages.c
 delete mode 100644 src/mate-languages.h
```
Are you sure deleting mate-languages.c/h is fine?

**Comment by zhuyaliang** [comment]
The use of mate-languages.c is because my local mate is not updated and needs to contain these two files.This is a single instance service and can only one  run a user-admin process at the same time

**Comment by raveit65** [comment]
Ok, mate-desktop-devel with https://github.com/mate-desktop/mate-desktop/commit/ecf2fbdb7cbad7f8e7dfef8efcbce82308739c02
is installed here.

**Comment by raveit65** [comment]
```
[rave@mother ~]$ user-admin
Segmentation fault (core dumped)
```

**Comment by raveit65** [comment]
``
(gdb) run
Starting program: /usr/bin/user-admin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffec28a700 (LWP 15196)]
[New Thread 0x7fffeba89700 (LWP 15197)]
Detaching after fork from child process 15198.

Thread 1 "user-admin" received signal SIGSEGV, Segmentation fault.
tcache_get (tc_idx=0) at malloc.c:2943
2943	  tcache->entries[tc_idx] = e->next;
(gdb) thread apply all bt full
```
full stacktrace is here:
https://www.dropbox.com/s/yxcbgs3pqo8q64s/user-admin-stack-trace?dl=0

**Comment by zhuyaliang** [comment]
Thank you very much for your help. I saw the GDB output, because the number of languages exceeded the size of the array, resulting in segment errors. Now I use the hash table to record the supported language。It may be because we have different operating environments. I can't reproduce some of the problems

**Comment by zhuyaliang** [comment]
@raveit65 If you have any questions and suggestions, please contact me. I will make timely changes.

**Comment by zhuyaliang** [comment]
@raveit65 
I am very glad to receive your reply.

1. In the next release, I'm going to remove the input box for the old password because it involves complex permission issues.

2.Automatic login doesn't work. It may be related to your DM. I will try to solve this problem.

3.Rest assured that all user changes will be saved.

4.The image selection is designed as a window without frame which I think would be more beautiful, and when the user does not make any choices, click on other spaces, and the window will automatically disappear

5.It's a good idea to add an option to use local images, and I'll add a selection button in the next release. Click to select local pictures.

Thank you very much for your advice. I will contact you again when everything is ready.

**Comment by raveit65** [comment]
> 2.Automatic login doesn't work. It may be related to your DM. I will try to solve this problem.

Personal, i am not a friend of automatic login. I think it's more an insecure feature for fool people.
I guess auto-login works with gdm, right?
I think you need to add configs for several DMs. 
As i said , i don't care much about it, drop it if it is too much work to support all kind od DM's, imo.

> 3.Rest assured that all user changes will be saved.

My confusion come from missing close button in main window.
Closing an application means to save current state, .......well i am oldschool :)

I am fine with 4.

I am happy to test more and i will add it to official fedora if it is ready for production ;)

**Comment by lukefromdc** [comment]
One obvious case for auto-login is an encrypted machine that requires a passphrase to unlock all partitions just to boot. Quite often (as with laptops) these are single-user machines, and encrypted machines cannot safely be left running or suspended when unguarded due to the "cold boot attack." Thus, a login passphrase on a single-user computer that already requires an encryption passphrase adds no further security.

**Comment by lukefromdc** [comment]
Any time the box is encrypted, a login passphrase will be seen as an utter nuisance, and further yet, the user passphrase (still needed for sudo) must never match the disk passphrase, as a hash reversing attack on /etc/shadow is much less computationally intensive than trying LUKS passphrases and having to actually try to get a key each time.  Also, users would be deterred from using the long, complex passphrase needed to defeat state-level attackers brute-force attempts if they have to use it for sudo as well.

Using a USB drive for /boot on an encrypted box stops one out of three attack vectors: Stops initramfs/kernel/bootloader replacement(evil maid) but not firmware replacement("evil cook," blocked by boot-guard on some Intel boards), and nothing stops hardware keyloggers except physically looking for them. The hardware keylogger is the most common attack in the field, as it requires zero prior information about the target.

**Comment by zhuyaliang** [comment]
@raveit65
Sorry to let you wait so long。
Now  already supported the selection of pictuces from the local， And don't need to enter old passwords when changing passwords.
You're right,Automatic login is more suitable for gdm. Automatic login is realized by act_user_set_automatic_login () function provided by accountsservice.Currently, "Accountsservice" only supports automatic login of gdm, I have already made suggestions to the  “Accountsservice” authors, I hope they can add more support
all changes take effect in real time, and i think this is more convenient for the user.

**Comment by lukefromdc** [comment]
Auto-login also works on lightdm, I haven't had any problems with it other than the time to set it up years ago.

**Comment by raveit65** [comment]
Yes, but lightdm use his own config path which is different from accountsservice.

**Comment by raveit65** [comment]
@zhuyaliang 
Thanks, adding a local user image works fine now
And i don't need to enter the old password.
But i don't see my pass word in clear text in the password dialog, which is bad if i use the built-in password generator.
Or what happens if i click on the icon right in the password field?
![user-admin-password](https://user-images.githubusercontent.com/961604/44450979-aa24b080-a5f2-11e8-9fa3-e1addfae9d0e.jpg)

And you don't like to add a close button to main dialog?
![user-admin](https://user-images.githubusercontent.com/961604/44451130-1c959080-a5f3-11e8-9952-f00ef2afcfab.jpg)

**Comment by raveit65** [comment]
Btw. i forgot to say. Why installation copy this dir?
```
[rave@mother user-admin-test]$ ls -l /usr/share/user-admin/data/
insgesamt 16
drwxr-xr-x 2 root root 4096 22. Aug 09:52 face
drwxr-xr-x 2 root root 4096 22. Aug 09:52 icon
-rw-r--r-- 1 root root  571 22. Aug 09:36 meson.build
-rw-r--r-- 1 root root  196 18. Jul 11:03 user-admin.desktop.in
```

**Comment by zhuyaliang** [comment]
@raveit65 
1 Auto-login:
    I understand what you mean. Automatic login can be done by setting up lightdm.conf manually, but I think using the Accountsservice to set up automatic login is the best choice. I have submitted to Accountsservice patch that can support lightdm automatic login. I believe lightdm will be able to use the auto login function happily in the near future.
2 clear text
   When you enter the password manually, the password is not displayed in clear text, which can increase the security.Sorry, this is my negligence. I didn't join icon tooltip。The right icon in the password can provide password auto generation function, generated password in plaintext format, You can download the latest code and test it.
3 installation copy dir
   The face directory provides the default user avatar.
![5](https://user-images.githubusercontent.com/36913152/44566555-c8c8aa00-a7a0-11e8-9eda-d2ed760d78ec.png)
   icon provides service icons，

**Comment by lukefromdc** [comment]
Lightdm is still rather important, as GDM is tightly coupled to GNOME, requires gnome-shell, uses its own screenlocker and so on. Just changing the background image in GDM can be a royal fsck job or at least was as of the last version. There is also MDM(GDM 2 fork), not sure if that was ever ported to GTK 3 or not.

**Comment by raveit65** [comment]
> There is also MDM(GDM 2 fork),

Are you sure that linuxmint use this nowadays?
As far i know the forked unity-greeter, renamed it to slickgreeter and use it as frontend for lightdm.
I don't think that mdm is relevant.

**Comment by zhuyaliang** [comment]
@raveit65 I think when close the window, can click "X" in the upper right corner. There's no need to set a button individually, but I can add a button if you need it.

**Comment by raveit65** [comment]
@zhuyaliang 
I can also use alt+F4 for closing the window ;)   .... but keep in mind that a linux beginner can be confused if there isn't a traditional button for closing the window.

**Comment by zhuyaliang** [comment]
@raveit65 
OK, I will add a close button, this button only provides the function of destroying the window.

**Comment by zhuyaliang** [comment]
@raveit65 
How about putting this button in this place? Or do you have better attention?
![2](https://user-images.githubusercontent.com/36913152/44594263-3ce26c80-a7f8-11e8-806a-ba98a2908200.png)

**Comment by raveit65** [comment]
@zhuyaliang 
Perfect :)

**Comment by zhuyaliang** [comment]
@raveit65 
ok.When I complete the function( g_signal_connect), I will contact you

**Comment by zhuyaliang** [comment]
@raveit65 
I have uploaded the code, you can test it.
Thank you for your help and testing.

**Comment by raveit65** [comment]
@zhuyaliang 
Thanks for your work, button is fine :)

I think basic functions are working now, so i have only a few minor suggestions/issues.
1 . `sudo ninja -C build install` installs the data folder from download dir.
```
[root@mother rave]# ls -l /usr/share/user-admin/data/
insgesamt 16
drwxr-xr-x 2 root root 4096 25. Aug 16:59 face
drwxr-xr-x 2 root root 4096 25. Aug 16:59 icon
-rw-r--r-- 1 root root  571 22. Aug 09:36 meson.build
-rw-r--r-- 1 root root  196 18. Jul 11:03 user-admin.desktop.in
```
3. And maybe it's better to rename the dir to /usr/share/mate-user-admin/ ?
This will group the application to all other applications in /usr/share/.
2. An icon for menu-entry is missing.
3. Main window called `Mate User Manage`, I am not a native english speaker, but is this correct english?
@lukefromdc ^^^?

**Comment by lukefromdc** [comment]
I am not a language expert but I don't see any problems with the main window being called "Mate User Manage" in English. "Mate User Manager" might be a bit clearer but not big deal either way.

**Comment by zhuyaliang** [comment]
An icon for menu-entry is missing.
Are you talking about this? If so, I have made some changes.
![image](https://user-images.githubusercontent.com/36913152/44624242-11a46e00-a91b-11e8-9f07-d98b1f83d2e7.png)

**Comment by raveit65** [comment]
Yes, i meant the icon specification in desktop file.
But you change doesn't help to display the icon in menus or mate-control-center.
![mate-user-admin](https://user-images.githubusercontent.com/961604/44626571-e885dc80-a91e-11e8-87ad-b0bf4d2e4f30.jpg)
You need to install an extra icon with different sizes (16/22/24/32/48px) to /usr/share/icons/hicolor/ dir.
I created the icons in different sizes for you https://www.dropbox.com/s/5xanedeqo5nmxl2/user-admin-icons.tar.xz?dl=0
Install dirs should be:
/usr/share/icons/hicolor/16x16/apps/user-admin.png
/usr/share/icons/hicolor/22x22/apps/user-admin.png
/usr/share/icons/hicolor/24x24/apps/user-admin.png
/usr/share/icons/hicolor/32x32/apps/user-admin.png
/usr/share/icons/hicolor/48x48/apps/user-admin.png

And in desktop file use 
Icon=user-admin
After installation or copying do update the icon-cache like this.
```
[root@mother rave]# gtk-update-icon-cache /usr/share/icons/hicolor/
gtk-update-icon-cache: Cache file created successfully.
```
That's it.
![mate-user-admin-good-icons](https://user-images.githubusercontent.com/961604/44626827-da868a80-a923-11e8-8466-388683e3e357.jpg)

Beside from this you need to change the dir to `usr/share/mate-user-admin/data/`at more places
```
src/main.c:15:    Pixbuf = gdk_pixbuf_new_from_file("/usr/share/user-admin/icon/user-admin.png",&Error);
src/user.h:28:#define  DEFAULT    "/usr/share/user-admin/face/Default.png"
```

I would also change the name in desktop file.
Name=User admin  --> MATE User Manager

**Comment by zhuyaliang** [comment]
@raveit65 
Thank you very much for your help.I made changes according to your help prompt.You can test it and see at the running effect。
Thank you again for your help and advice these days.

**Comment by raveit65** [comment]
This works fine and thanks again for your fine work.
Time for a 0.1 release?  :)
For remaining issues i will use your repo at github.
There i can also do pull requests ;)

**Comment by raveit65** [comment]
Thanks a lot, i will use a release for fedora if it is available.
