### ISSUE TITLE
Midori as the default browser for Mate desktop

### ISSUE THREAD

**Issue by anasram** [mate-desktop/mate-desktop#351]
It seems like Midori browser no longer belongs to elementary apps family anymore.

Anyway, don't you think it's time to take the initiative and adopt Midori as a member of Mate apps family?

I think Mate desktop deserves to have its own browser; a native GTK browser, that integrates deeply with Mate functions and harmonises with its classic spirit.

![classic-midori](https://user-images.githubusercontent.com/12219238/50976881-ba81ed00-14f9-11e9-877d-3dbdcc64fb61.png)

**Comment by raveit65** [comment]
I am using firefox and we don't set any webbrowser as default.

**Comment by lukefromdc** [comment]
Same here, and in my case the advantage of Firefox is the abilty to set up a full suite of ad and tracker blocking privacy extensions.

**Comment by anasram** [comment]
I know. Firefox works fine for most users, but I'm talking here about a typical GTK+ desktop environment.

Firefox is meant to be an independent application, works in different platforms, thus, it probably dosn't take advantage of specific-platform resources and features.

Think of a set of GTK applications, like XReader, Midori, Zim, and even Gnumeric, depend all together on WebKitGTK library as a common layout engine.

Real integration and dependency leads to three main benefits: [maintainability, usability, and performance](https://richstyle.org/?software-engineering/software-engineering-en).

I realise that adopting such a browser in Mate desktop probably won't be a simple decision, but it deserves. Therefore, please think about it.

**Comment by raveit65** [comment]
Setting default applications are set by mime types settings. This can be done by your MATE distro maintainer or by an admin for his company systems. An example for fedora.
https://src.fedoraproject.org/cgit/rpms/mate-desktop.git/tree/mate-mimeapps.list
We never forced users to use specific applications like web-browsers, audioplayer, text-editors, office applications of any other application.

Are you developer of Midori browser?

**Comment by lukefromdc** [comment]
I for one do not like the idea of setting a non-privacy aware browser as a default for anything, as I consider the majority of ad-supported websites malicious and dangerous.

**Comment by anasram** [comment]
> We never forced users to use specific applications like web-browsers, audioplayer, text-editors, office applications of any other application.

Sure, I'm just talking here about an integrated desktop environment.

> Are you developer of Midori browser?

No, I even don't use it, but I like it's design and performance.

> I for one do not like the idea of setting a non-privacy aware browser as a default for anything, as I consider the majority of ad-supported websites malicious and dangerous.

Midori is definitely not mature enough, especially in terms of critical factors like security and privacy.

Adopting it doen't mean just setting it as a default browser; it means basically working on developing it.

**Comment by raveit65** [comment]
> Adopting it doen't mean just setting it as a default browser; it means basically working on developing and improving it.

Sorry, i don't need another job ;)
Why not doing that for yourself?

**Comment by anasram** [comment]
Because I don't need another job either 😊

Well, actually I'm not a GTK developer, and Midori has its own developer, besides, it seems the project is still active.

The only thing you will need to do then is to share a common vision with Midori's developer; Christian Dywan, with a view to adopt the integration with MATE desktop in his work.

**Comment by mhussaincov** [comment]
hi there,
if you mean replaceing firefox then nope, Midori last i checked was
not accessible with orca the screen reader.
firefox is however.
my thoughts.
Majid

On 15/01/2019, Anas R. <notifications@github.com> wrote:
> Because I don't need another job either 😊

>

> Well, actually I'm not a GTK developer, and Midori has its own developer,
> besides, it seems the project is still active.

>

> The only thing you will need to do then is to share a common vision with
> Midori's developer; Christian Dywan, with a view to adopt the integration
> with MATE desktop in his work.

>

>

> --

> You are receiving this because you are subscribed to this thread.

> Reply to this email directly or view it on GitHub:

> https://github.com/mate-desktop/mate-desktop/issues/351#issuecomment-454587074


-- 
kind regards,
Majid Hussain

**Comment by lukefromdc** [comment]
I think it's clear we are not doing this
