### ISSUE TITLE
Add horizontal sorting

### ISSUE THREAD

**Issue by Translator5** [mate-desktop/mate-desktop#377]
#### Expected behaviour
Sort my workspace starters and files horizontally. 

#### Actual behaviour
There is just the option of vertical sorting in the drop-down-menu.

#### Steps to reproduce the behaviour
Right-click on desk and look for sorting.

#### MATE general version
Mate: 1.20.4

#### Package version
Brisk Menu Starter: 0.5.0
Mate-Panel: 1.20.5

#### Linux Distribution
Manjaro Linux 64bit
Kernel: 4.19.30-1-Manjaro x86_64

**Comment by raveit65** [comment]
Wrong project!
https://github.com/solus-project/brisk-menu
