### ISSUE TITLE
Wrong builder files from languages in 1.23.0 tarball

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-desktop#382]
#### Expected behaviour
No *.gmo files in tarball.

#### Actual behaviour
```
[rave@mother mate-desktop]$ ls -l mate-desktop-1.23.0/po/
insgesamt 9196
-rw-r--r-- 1 rave rave  1959 22. Apr 00:14 af.gmo
-rw-rw-r-- 1 rave rave 39062 22. Apr 00:14 af.po
-rw-r--r-- 1 rave rave 28760 22. Apr 00:14 am.gmo
-rw-rw-r-- 1 rave rave 53116 22. Apr 00:14 am.po
-rw-r--r-- 1 rave rave  4218 22. Apr 00:14 an.gmo
-rw-rw-r-- 1 rave rave 40146 22. Apr 00:14 an.po
-rw-r--r-- 1 rave rave 38998 22. Apr 00:14 ar.gmo
-rw-rw-r-- 1 rave rave 58730 22. Apr 00:14 ar.po
-rw-r--r-- 1 rave rave 35562 22. Apr 00:14 as.gmo
-rw-rw-r-- 1 rave rave 61614 22. Apr 00:14 as.po
<cut>
-rw-r--r-- 1 rave rave  4293 22. Apr 00:14 wa.gmo
-rw-rw-r-- 1 rave rave 40034 22. Apr 00:14 wa.po
-rw-r--r-- 1 rave rave 10162 22. Apr 00:14 xh.gmo
-rw-rw-r-- 1 rave rave 42653 22. Apr 00:14 xh.po
-rw-r--r-- 1 rave rave  1246 22. Apr 00:14 yi.gmo
-rw-rw-r-- 1 rave rave 38863 22. Apr 00:14 yi.po
-rw-r--r-- 1 rave rave  1655 22. Apr 00:14 yo.gmo
-rw-rw-r-- 1 rave rave 38929 22. Apr 00:14 yo.po
-rw-r--r-- 1 rave rave 35714 22. Apr 00:14 zh_CN.gmo
-rw-rw-r-- 1 rave rave 52700 22. Apr 00:14 zh_CN.po
-rw-r--r-- 1 rave rave 22195 22. Apr 00:14 zh_HK.gmo
-rw-rw-r-- 1 rave rave 47195 22. Apr 00:14 zh_HK.po
-rw-r--r-- 1 rave rave 37022 22. Apr 00:14 zh_TW.gmo
-rw-rw-r-- 1 rave rave 53578 22. Apr 00:14 zh_TW.po
-rw-r--r-- 1 rave rave  1780 22. Apr 00:14 zu.gmo
-rw-rw-r-- 1 rave rave 38968 22. Apr 00:14 zu.po
```
Those *.gmo files aren't present in 1.21.1 tarball and the error is caused by porting using inittool to gettext for building languages.
https://github.com/mate-desktop/mate-desktop/pull/376

#### Steps to reproduce the behaviour
./autogen.sh && make && make distcheck

#### MATE general version
1.23.0

#### Package version
mate-desktop-1.23.0

#### Linux Distribution
fedora

#### Link to downstream report of your Distribution
1.23 isn't built for fedora.

**Comment by yetist** [comment]
@raveit65 

I think this is a bug in gettext.
Here is a discussion: https://lists.gnu.org/archive/html/bug-gnu-utils/2006-11/msg00139.html

The patch to fix gettext as follows:
```
--- old/Makefile.in.in 2019-05-14 15:21:51.455784771 +0800
+++ new/Makefile.in.in     2019-05-14 15:22:09.402334821 +0800
@@ -73,7 +73,7 @@
 DISTFILES.common = Makefile.in.in remove-potcdate.sin \
 $(DISTFILES.common.extra1) $(DISTFILES.common.extra2) $(DISTFILES.common.extra3)
 DISTFILES = $(DISTFILES.common) Makevars POTFILES.in \
-$(POFILES) $(GMOFILES) \
+$(POFILES) \
 $(DISTFILES.extra1) $(DISTFILES.extra2) $(DISTFILES.extra3)
 
 POTFILES = \
```
If we patched the OS on travis, we can get a clean tarballs.

**Comment by raveit65** [comment]
Report is from 2006, still wondering that we run in this issue after 13 years.

**Comment by yetist** [comment]
https://lists.gnu.org/archive/html/bug-gnu-utils/2006-11/msg00143.html

>Santiago Vila writes:
>> If this is not a bug, then it seems a documentation bug somewhere.
>
>The *.gmo files are required when a maintainer does a distribution.
>Therefore see documentation section "Release Management". It documents
>a Makefile target 'update-po'. If you look into the Makefile, you will
>also see a Makefile target 'update-gmo'.
>
>Bruno

**Comment by yetist** [comment]
Maybe someone thinks this is a feature, not a bug.

**Comment by raveit65** [comment]
Ok, i checked installation from this tarball and the .gmo files wont be installed with using autotools/meson or in my rpms.
So, in the end only the size of a tarball will be increased, and nobody needs this files... :)
Should we care about it if they think it is a feature?
Where we need to add your fix , at https://github.com/mate-desktop/mate-dev-scripts/tree/master/travis  ?
Or do we have to update every travis.yml?

**Comment by yetist** [comment]
I don't think it's worth much to solve this issue.
If we switch to meson, the problem disappears. The tarball created with `ninja dist` is clean.
If we really care about this, we can create a script and update every `.travis.yml` file, just like https://github.com/mate-desktop/mate-dev-scripts/tree/master/travis/debian.sh or fedora.sh does.

**Comment by raveit65** [comment]
Indeed, problem doesn't exists if we use `ninja -C build dist`
Now i understand why nobody cares about, eg. gnome.
I am fine with ignoring the issue, because port to `gettext` is only in master branch and stable 1.22 branch without meson isn't affected.

**Comment by raveit65** [comment]
That means we need to switch to to use `ninja -C build dist` for Travis master branch , if port to meson is done for a repo.
