### ISSUE TITLE
When searching in File Open dialog, first key press is entered twice

### ISSUE THREAD

**Issue by rimu** [mate-desktop/mate-desktop#402]
#### Expected behaviour
Using any app, I can open files by using the File Open dialog. After opening the dialog box I can type anything and the files shown inside the dialog will be filtered to only show those files that match what I typed.

#### Actual behaviour
The first letter of what I type is duplicated. If I type 'maps' the letters 'mmaps' will be shown in the search box at the top of the File Open dialog and the files will be filtered by 'mmaps' instead of 'maps'

#### Steps to reproduce the behaviour
Using any app, such as Firefox or xed go to the File menu and choose Open. A file open dialog box will appear. Do not change to another directory by using the folder pane on the left. Type any sequence of characters and observe the first letter is shown twice in the search box at the top of the dialog.
A screenshot of this behaviour is shown here: https://rimu.geek.nz/mint-bug.png

If you choose any folder on the left pane before typing then this bug will not occur.

#### MATE general version
Whatever version comes with Linux Mint 19.1 Tessa. 1.20.1??

#### Linux Distribution
Linux Mint 19.1 Tessa

**Comment by lukefromdc** [comment]
I cannot duplicate this on Debian Unstable with a local build of GTK 3.24.10 . The dialog in question I'm pretty sure comes from GTK itself, thus all all probability this is a bug in the GTK 3 version you have

**Comment by rimu** [comment]
I installed gedit and the same problem occurs. You're right it's GTK 3, or the way GTK 3 is used in Mate.

**Comment by lukefromdc** [comment]
Since I don't get this on GTK 3.24.10 GTK devs must have already fixed it. If you can install this (or your distro ever ships it) this will be fixed on your machine.
