### ISSUE TITLE
mate-desktop 1.23.3 tarball was published on the 1.22 folder

### ISSUE THREAD

**Issue by kyrios123** [mate-desktop/mate-desktop#422]
This isn't a mate-desktop issue as such, but I don't know where else I could report this.
The mate-desktop 1.23.3 tarball was accidentally published in the 1.22 release folder

https://pub.mate-desktop.org/releases/1.22/

CC: @raveit65

**Comment by raveit65** [comment]
Thanks for info. Tarball is removed from 1.22 folder.
