### ISSUE TITLE
Wrong version reported in meson build of 1.24

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-desktop#429]
#### Expected behaviour
Both autotools and meson builds of Feb 7 release of mate-desktiop 1.24 show 1.24 version in mate-about

#### Actual behaviour
Build with autotools shows version 1.24.0 but build with meson and and 1.23.3 shows up as version in mate-about

#### Steps to reproduce the behaviour
Build 1.24 from git master 2-7-2020 with meson, install, run mate-about

#### MATE general version
1.23/1.24

#### Package version
mate-desktop 1.24.0 from git master 2-7-2020, local build

#### Linux Distribution
Debian Unstable

#### Link to downstream report of your Distribution
None as this is a local build

**Comment by raveit65** [comment]
Opps, fixed with https://github.com/mate-desktop/mate-desktop/commit/10c192c904f9889153e2788bef9b2520b3068864

**Comment by lukefromdc** [comment]
I can confirm this is fixed, closing. Are we going to re-release over this or wait until something else forces a 1.24.1 release?

**Comment by raveit65** [comment]
This commit is the v1.14.0 tag. So it is in released tarball.
