### ISSUE TITLE
Option of Launch using dedicated Graphics Card in the Ubuntu MATE

### ISSUE THREAD

**Issue by canalocaradoti** [mate-desktop/mate-desktop#453]
Hi everyone, everything fine? (if this topic is in the wrong place, please move to the correct place).

I'm using Ubuntu MATE 20.04.1 (version 1.24.0-2 of MATE), and the configuration of my Dell 7559 laptop is: Intel Core i5 (6th Gen) 6300HQ / 2.3 GHz; 16 GB DDR3L SDRAM 1600 MHz in dual channel; HD 1TB and 240GB SSD and NVIDIA GeForce GTX 960M 4GB GDDR5 SDRAM. Before I was using Ubuntu 20.04.1 with GNOME (3.36), but I felt that the system did not flow properly on my laptop. So far I am enjoying the performance I am having, except for two "problems". The first is in relation to the icons for the Portuguese language (Brazil), but it is not the object of the post.

What I miss about Ubuntu MATE, is the option to be able to right-click the app and open it with the dedicated GPU, just like in GNOME, with the "Launch using dedicated Graphics Card" option. So I would like to know if this functionality is on the "radar" to be implemented.

I'm available for testing if you need

Att

Ricardo.

**Comment by raveit65** [comment]
Wrong organisation. Home of Ubuntu MATE is here https://github.com/ubuntu-mate
