### ISSUE TITLE
No icon illustration when ejecting a CD.

### ISSUE THREAD

**Issue by MosaicPicture** [mate-desktop/mate-desktop#456]
#### Expected behaviour
 
That the "ejecting CD" icon appears in the little notification box (as it does when increasing volume for instance). 

#### Actual behaviour

The notification box is empty, no icon at all. 

#### Steps to reproduce the behaviour

Just press your CD ejection button on your keyboard (if you have one, which is not common). 

#### MATE general version

1.24.0

#### Linux Distribution

Linux Mint 20 Ulyana

#### Link to downstream report of your Distribution

https://termbin.com/ndxw

![Capture du 2020-10-18 15-43-40](https://user-images.githubusercontent.com/73066351/96369337-99800e80-1159-11eb-824a-23d09ec78c92.png)
![Capture du 2020-10-18 15-50-23](https://user-images.githubusercontent.com/73066351/96369383-d3511500-1159-11eb-8f94-602cca7b111d.png)

**Comment by rbuj** [comment]
I was unable to reproduce your issue, you may be using an icon theme that doesn't provide the icon.

![VirtualBox_11 Fedora Rawhide_18_10_2020_19_34_07](https://user-images.githubusercontent.com/10171411/96375496-a01e7e00-1179-11eb-949b-329588dbd5c1.png)

**Comment by MosaicPicture** [comment]
> I was unable to reproduce your issue, you may be using an icon theme that doesn't provide the icon.
> 
> ![VirtualBox_11 Fedora Rawhide_18_10_2020_19_34_07](https://user-images.githubusercontent.com/10171411/96375496-a01e7e00-1179-11eb-949b-329588dbd5c1.png)

Well it seems that you're right. I was using the built-in _Mint-Y_ theme from Linux Mint. 
Just switched to the "old" Mint-X and I got an icon when pressing the eject key. 

So  CDs are really a thing of the past... lol. :( 

Thank you for your answer!
