### ISSUE TITLE
No dark theme for gtk4 applications with BlackMATE theme.

### ISSUE THREAD

**Issue by genes1122** [mate-desktop/mate-desktop#476]
#### Expected behaviour
Selecting dark theme in gtk4 app works.

#### Actual behaviour
No dark theme available

#### Steps to reproduce the behaviour
Install easyeffects, switch to BlackMATE theme, toggle dark theme in easyeffects app.  Switch to Adwaita-dark and it works.

#### MATE general version
1.24

#### Package version
1.24.1-1.9

#### Linux Distribution
openSUSE

#### Link to bugreport of your Distribution (requirement)
https://github.com/wwmm/easyeffects/issues/1106#issuecomment-902193164

**Comment by lukefromdc** [comment]
I didn't know this worked in GTK3 either, I don't recall ever working on support for light/dark theming selection in Blackmate nor.seeing this im our other themes.

**Comment by raveit65** [comment]
Mate doesn't support gtk4 and our themes don't support light/dark switching.
Feel free to rewrite BackMate to support this.
Anyway, not an issue.
