### ISSUE TITLE
System Program Problem Detected

### ISSUE THREAD

**Issue by FOSSBOSS** [mate-desktop/mate-desktop#487]
#### Expected behaviour:
A dialog with details

#### Actual behaviour
message box appears with cryptic message, and no further detail

#### Steps to reproduce the behaviour
Have a crash log, in /var/crash.
reboot

#### MATE general version
1.24.0

#### Package version
1.24.0

#### Linux Distribution
Ubuntu Mate 20.04

#### Link to bugreport of your Distribution (requirement)
Im not even sure Mate Desktop is the right project. see issue about cryptic message
![whatProblem](https://user-images.githubusercontent.com/12141764/136679349-1e96619c-2842-4f8e-b37e-1f89ce873bbd.png)

this message box appears on boot. every time. Or it did, until I went into /var/crash and deleted my crash logs.

here is a post I made about it on askubuntu
https://askubuntu.com/questions/1368327/problem-what-problem/1368386#1368386

**Comment by zhuyaliang** [comment]
This is not mate's problem.
you can completely turn off apport to get rid. Edit the configuration file at ```/etc/default/apport```.
Just set the value of enabled to 0, and this will disable apport.
```enabled=0```
Save the file and close it. From the next boot onwards, there should be no error messages ever. If you do not want to restart the system then restart apport from the command line.
```sudo restart apport```

**Comment by FOSSBOSS** [comment]
getting rid of it isnt the issue, but a lack of detail in the reporting. I'll go check out apport.
