### ISSUE TITLE
mate-volume-control-status-icon keeps crashing on hover

### ISSUE THREAD

**Issue by ifohancroft** [mate-desktop/mate-desktop#494]
#### Expected behaviour

1. Hover on the icon in the tray
2. It doesn't crash

#### Actual behaviour
1. Hover on the icon in the tray
2. Somtimes it crashes

#### Steps to reproduce the behaviour
Hover on the icon in the tray (it won't crash every time. Maybe once or twice per day or every other day)

#### MATE general version
1.26.0

#### Package version
mate-media 1.26.0-1

#### Linux Distribution
Manjaro

#### Link to bugreport of your Distribution (requirement)
I don't understand what this requirement is asking of me.

Here is the output when the icon crashes:
```
(mate-volume-control-status-icon:116748): Gtk-WARNING **: 19:30:43.174: Calling gtk_widget_realize() on a widget that isn't inside a toplevel window is not going to work very well. Widgets must be inside a toplevel container before realizing them.

(mate-volume-control-status-icon:116748): GLib-GObject-CRITICAL **: 19:30:43.176: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(mate-volume-control-status-icon:116748): Gdk-CRITICAL **: 19:30:43.176: gdk_window_get_scale_factor: assertion 'GDK_IS_WINDOW (window)' failed
**
Gtk:ERROR:../gtk/gtk/gtkwidget.c:5875:gtk_widget_get_frame_clock: assertion failed: (window != NULL)
Bail out! Gtk:ERROR:../gtk/gtk/gtkwidget.c:5875:gtk_widget_get_frame_clock: assertion failed: (window != NULL)
```

**Comment by ifohancroft** [comment]
I opened this in the wrong repo so I am closing it now.

**Comment by raveit65** [comment]
> I don't understand what this requirement is asking of me.

No open downstream report at your distro to inform distro maintainer, no service by me.
By the way, i can't reproduce this with fedora.
