### ISSUE TITLE
Control Center, Hardware, Power Management: issues with Russian localization - not translated string

### ISSUE THREAD

**Issue by HectorB-2020** [mate-desktop/mate-desktop#499]
#### Expected behaviour
"**Power Management Preferences**", tab "**On Battery Power**"
"**Keyboard**"
  [ ] Reduce keyboard backlight 
should be translated to Russian

#### Actual behaviour
Even with 
```
LANG=ru_RU.UTF-8
LANGUAGE=ru_RU.UTF-8
```
"**Power Management Preferences**", tab "**On Battery Power**"
"**Keyboard**"
  [ ] Reduce keyboard backlight
is left in English

#### Steps to reproduce the behaviour
Run `mate-power-preferences`, switch to tab  "**On Battery Power**"

#### MATE general version
MATE 1.26.0

#### Package version
1.26.0

#### Linux Distribution
Ubuntu 21.10

**Comment by raveit65** [comment]
Again, we're using transifex for our translations. We can't fix it here !
Please become a member of your language team at transifix and fix translations there.
https://www.transifex.com/mate/MATE/languages/
