### ISSUE TITLE
Control Center, Hardware, Keyboard Preferences: issues with Russian localization - not translated string

### ISSUE THREAD

**Issue by HectorB-2020** [mate-desktop/mate-desktop#500]
#### Expected behaviour
"**Keyboard Preferences**", "**Accessibility**", button "**Audio Feedback...**"
"**Caps Lock**"
 [ ] Beep when pressing a key while CapsLock is active
should be translated to Russian

#### Actual behaviour
Even with
```
LANG=ru_RU.UTF-8
LANGUAGE=ru_RU.UTF-8
```
"**Keyboard Preferences**", "**Accessibility**", button "**Audio Feedback...**"
"**Caps Lock**"
 [ ] Beep when pressing a key while CapsLock is active
is left in English

#### Steps to reproduce the behaviour
Run `mate-keyboard-properties`, switch to tab "**Accessibility**", click on button "**Audio Feedback...**

#### MATE general version
MATE 1.26.0

#### Package version
1.26.0

#### Linux Distribution
Ubuntu 21.10 with latest updates

**Comment by raveit65** [comment]
Again, we're using transifex for our translations. We can't fix it here !
Please become a member of your language team at transifix and fix translations there.
https://www.transifex.com/mate/MATE/languages/
