### ISSUE TITLE
Control Center, Hardware, Displays: issues with Russian localization - not translated items

### ISSUE THREAD

**Issue by HectorB-2020** [mate-desktop/mate-desktop#501]
#### Expected behaviour
Control Center -> Hardware -> "**Monitor Preferences**" (RU: "**Параметры монитора**")
 - _Scaling_
 - _auto detect_
  These two strings above should be translated to Russian.

#### Actual behaviour
 - _Scaling_
 - _auto detect_
   These two strings above are left in English even under Russian localization.

#### Steps to reproduce the behaviour
Run `mate-display-properties`.

#### MATE general version
MATE 1.26.0

#### Package version
1.26.0

#### Linux Distribution
Ubuntu 21.10 with latest updates

**Comment by mbkma** [comment]
see https://wiki.mate-desktop.org/contributing/translation/getting-started/ on how to help with translation.

**Comment by raveit65** [comment]
Please stop raising translations issues here!
Again, we're using transifex for our translations. We can't fix it here.
Please become a member of your language team at transifix and fix translations there.
https://www.transifex.com/mate/MATE/languages/
