### ISSUE TITLE
invalid desktop files distribution/arangment in brisk menu

### ISSUE THREAD

**Issue by Stormfinger** [mate-desktop/mate-desktop#511]
#### Expected behaviour
if all categories are mentioned then apps should show in all categories mentioned

#### Actual behaviour
*.desktop files arent shown in multiple places

#### Steps to reproduce the behaviour
try changing categorie in desktop file

#### MATE general version
mate-desktop/unstable,now 1.26.0-1 amd64 [installed,automatic]

#### Package version
mate-applet-brisk-menu/unstable,now 0.6.2-1 amd64 [installed,automatic]
mate-menus/unstable,unstable,now 1.26.0-2 all [installed,automatic]

#### Linux Distribution
debian sid

#### Link to bugreport of your Distribution (requirement)

**Comment by raveit65** [comment]
Brisk-menu is a third-party application and not part or MATE desktop, please open a report there.
