### ISSUE TITLE
Mate 22.04 does not change time to 12 format

### ISSUE THREAD

**Issue by maravento** [mate-desktop/mate-desktop#520]
#### Expected behaviour

change the time format from 24 to 12

#### Actual behaviour

does not change the time format from 24 to 12

#### Steps to reproduce the behaviour

![Captura de pantalla -2022-04-25 17-02-53](https://user-images.githubusercontent.com/14880802/165182509-154a3d46-8326-49ba-8172-cd1d5bada7ce.png)

conf:

![Captura de pantalla -2022-04-25 17-02-12](https://user-images.githubusercontent.com/14880802/165182504-418bd6d5-11dc-4112-bf93-645a3526577d.png)

![Captura de pantalla -2022-04-25 17-03-17](https://user-images.githubusercontent.com/14880802/165182511-1026f647-8c2f-44bb-9989-42cfd03b1798.png)

#### MATE general version

MATE 1.26.0

#### Linux Distribution

ubuntu mate 22.04

**Comment by zhuyaliang** [comment]
This is the setting of ```Gnome``` time format
```Mate``` does not have a ```schema``` for time formatting
You can convert the time format directly on the panel

**Comment by maravento** [comment]
> This is the setting of `Gnome` time format `Mate` does not have a `schema` for time formatting You can convert the time format directly on the panel

if you are going to answer this issue, take the time to document your answer and the procedure, so that the community is clear about the resolution of this problem

**Comment by rbargerhuff** [comment]
> this is the [correct answer](https://ubuntu-mate.community/t/set-the-date-time-indicator-to-12-hour-time/21567). run in terminal:
> 
> ```
> gsettings set org.ayatana.indicator.datetime time-format '12-hour'
> ```

This is the ONLY source I could find, via google, that indicates the CORRECT way of setting the clock in 22.04 of Ubuntu MATE to use 24 hour. Thank you!! 

Why can this NOT be toggled in Control Center: Indicators: Date and Time ?
