### ISSUE TITLE
applet to mount partition

### ISSUE THREAD

**Issue by Stormfinger** [mate-desktop/mate-desktop#521]
#### Expected behaviour
i wish partitions would be listed vertical ..thus avoiding panell movement when there are several panells and partitions to mount

#### Actual behaviour
Partitions are listed horizontal

#### Steps to reproduce the behaviour
add applet for mounting partitions to panel

#### MATE general version
latest for debian bookworm

#### Package version
latest for debian bookworm

#### Linux Distribution
debian bookworm

#### Link to bugreport of your Distribution (requirement)
none

**Comment by raveit65** [comment]
Applet is part of mate-applets and called mount-applet.
