### ISSUE TITLE
Add users preset panels configuration.

### ISSUE THREAD

**Issue by Stormfinger** [mate-desktop/mate-desktop#522]
#### Expected behaviour
to be able to quickly save set of panels and load if things get messy

#### Actual behaviour
turn to default and set things all from begining

#### MATE general version
debian bookworm

**Comment by lukefromdc** [comment]
Mate-tweak should allow you to do this. You did not state your distro but at least Ubuntu has that package, I think they may have originated it but not sure

**Comment by rubyFeedback** [comment]
A comment:

> You did not state your distro but at least Ubuntu has that package

Not everyone uses distros, though. I don't, for instance. I compile mate-desktop from source, from github, and that actually works really well. Perhaps it may be useful to combine the functionality of mate-tweak into mate-desktop somehow, and have a fairly lose policy in what it can combine (e. g. as suggested the ability to quickly save panels/configurations).

**Comment by zhuyaliang** [comment]
At present, ```mate desktop``` does not provide the backup and restore function of ```mate panel``` style. You can install other plug-ins

**Comment by Stormfinger** [comment]
hi i use plain bookworm ...with mate ...i found Mate-tweak installed. thank you.
