### ISSUE TITLE
How can I add gnome to my apt repo?

### ISSUE THREAD

**Issue by yap241986** [mate-desktop/mate-desktop#523]
How can I add gnome to my apt repo?

**Comment by yap241986** [comment]
I was confused I wanted to write mate

**Comment by yap241986** [comment]
Ok, but how can I add it to my apt repo?

**Comment by rbuj** [comment]
Thank you very much for asking your question here, but I recommend you to expose your  concerns to your local or global community before doing so here. Feel free to open a new issue, if you do so, please follow the template to report any issues related to this software repository.

**Comment by cwendling** [comment]
You probably have a package similar to `mate-desktop-environment`, `ubuntu-mate-desktop` or similar. Installing this usually would bring everything you need, and be included in the he regular repositories.
For more details, you should try your distributor's forums as they would know better.
