### ISSUE TITLE
You probably have a package similar to `mate-desktop-environment`, `ubuntu-mate-desktop` or similar. Installing this usually would bring everything you need, and be included in the he regular repositories.

### ISSUE THREAD

**Issue by yap241986** [mate-desktop/mate-desktop#524]
You probably have a package similar to `mate-desktop-environment`, `ubuntu-mate-desktop` or similar. Installing this usually would bring everything you need, and be included in the he regular repositories.
For more details, you should try your distributor's forums as they would know better.

__Originally posted by @cwendling in https://github.com/mate-desktop/mate-desktop/issues/523#issuecomment-1186167910__

If I do:
sudo apt download mate-desktop-environment 
It download the dependences or no?

**Comment by cwendling** [comment]
@yap241986 I'm sorry you can't answer in the old thread, but you should rather follow the advice @rbuj and I gave you to try and get answers in your Linux distribution's community, that will know better how MATE is integrated in their environment than we can.  We are not familiar with all distros there is and their differences; and the question you're asking is definitely very much of the how-that-distro-packaged-MATE kind.

PS: it's `apt install`, `apt download` will only fetch the packages, not install them.  But then again, that's a question for your distro, I just happen to know the answer but wouldn't for many others.
