### ISSUE TITLE
For graphical applications launched with the root user there is no text (as superuser) after the application name in the window title bar

### ISSUE THREAD

**Issue by adam083b** [mate-desktop/mate-desktop#532]
#### Expected behaviour

When starting an application with the root user there should be the text (as superuser) after the application name in the window title bar.
![screenshot](https://user-images.githubusercontent.com/10560975/190853636-bef14b5c-d90a-4e20-8431-50bb715131d9.png)

#### Actual behaviour

When starting an application with the root user there is no text (as superuser) after the application name in the window title bar.

#### Steps to reproduce the behaviour

Launch a graphical application with the root user.

#### MATE general version

v1.26.0

#### Package version

v1.26.0-1

#### Linux Distribution

Linux Mint 21 Vanessa 64-bit

**Comment by lukefromdc** [comment]
This is a CSD app where marco does not draw the decorations and nothing in MATE controls the window title

**Comment by adam083b** [comment]
Hello,

Sorry for my late reply, so you can close the ticket at your convenience.
What is a CSD app by curiosity?

Thanks

**Comment by mbkma** [comment]
CSD refers to client-side decoration: https://wiki.gnome.org/Initiatives/CSD
