### ISSUE TITLE
system logs me off

### ISSUE THREAD

**Issue by Stormfinger** [mate-desktop/mate-desktop#542]
#### Expected behaviour
shouldn't log me off

#### Actual behaviour
sometimes and its happening more and more...screen freezes mouse works but apps are frozen ..then my screen goes black and returns ..apps get sometimes responsive but more likely arent and im invited for a new login ..dont know if its another session or system logs me off but im welcomed at login screen 

#### Steps to reproduce the behaviour
work with computer for several hours including some hefty idle time mostly working with 3 apps: firefox, element, Clion i have some rather old simple radeon graphic card 

#### MATE general version
1.26

#### Linux Distribution
debian bookworm

**Comment by raveit65** [comment]
Maybe, you are a victim by system-oomd service?
See fedora report for more information. https://bugzilla.redhat.com/show_bug.cgi?id=2068699

**Comment by lukefromdc** [comment]
Could well be systemd-oomd, and whatever it is it sounds like xorg is crashing(or being terminated by the out of memory killer) thus killing the session. This is not a normal logoff

**Comment by Stormfinger** [comment]
i found element is guilty for this issue thank you for assistance
