### ISSUE TITLE
mate-notification: Failed to load module "window-decorations-gtk module"

### ISSUE THREAD

**Issue by alexeiol** [mate-desktop/mate-desktop#543]
#### Expected behaviour
No error message.

#### Actual behaviour

I installed OSSEC-HIDS today and I am getting every few minutes identical error reporting e-mails:

Subject: OSSEC Alert - Level 2 - Unknown problem somewhere in the system.

Message body:

Received From: debianvaio->/var/log/messages
Rule: 1002 fired (level 2) -> "Unknown problem somewhere in the system."
Portion of the log(s):

Dec 31 20:59:16 debianvaio mate-notificati[15518]: Failed to load module "window-decorations-gtk module" 

The only thing that changes from one message to the other is the date and [number].

Since the alert message is not very specific I would appreciate instructions to provide more useful information, since I am not an IT professional.

I Googled many variations of this error message and couldn't find anything related to it.

#### MATE general version
MATE 1.24.1

#### Package version
Not sure what this means.

#### Linux Distribution

Debian 11 (bullseye) 64-bit

#### Link to bugreport of your Distribution (requirement)
Also not sure.

**Comment by lukefromdc** [comment]
Initially researching this I see various references to a GTK module, to wayland, to appimage, and to KDE.

What window manager are you using? Also is this program coming from an appimage, a flatpack, or something similar?

**Comment by alexeiol** [comment]
Hi, @lukefromdc -- For starters, happy 2023!

> What window manager are you using?

Here is the output from cat /etc/X11/default-display-manager: /usr/sbin/lightdm

> Also is this program coming from an appimage, a flatpack, or something similar?

If you are referring to the display manager, I installed it from Debian's official repositories via apt. 

(Please, be patient if my answers are not as helpful as they should. I am not acquainted with all the "under the hood" technical details.)

**Comment by lukefromdc** [comment]
By window manager I meant marco,compiz,etc: the program that allows moving and resizing windows and draws the window borders(decorations).

No problem w being new,this stuff takes time to learn

**Comment by alexeiol** [comment]
Ah, ok! I am using marco -- I think it is the default window manager when you choose only the Mate Desktop option in Debian installer. 

I tried other desktops along the years - Gnome, Gnome 3, Unity, KDE, LXDE, XFCE  - but Mate proved to be the superior choice for my family and small publishing house. In a fresh Debian install, I don't even consider other options -- Mate is the only desktop I select.

**Comment by lukefromdc** [comment]
That suggests the app may be looking for a GTK module it should have depended on but can run without, and which MATE does not use.

**Comment by lukefromdc** [comment]
The notification comes from the app not from MATE, and GTK is provided by your distro and maintained by GNOME. MATE uses GTK 3 but does not provide it nor any module, so this issue is not in MATE.

If the notification daemon properly passes what the application gave it to the desktop notification window, it has done its job correcrlt

**Comment by alexeiol** [comment]
I found this thread https://github.com/flatpak/xdg-desktop-portal-gtk/issues/215. Since I do not use Flatpak, and it was the only dependency, I decided to uninstall the packages xdg-desktop-portal-* from my system. It stopped the log spam and, to this moment, doesn't seem to have broken anything.
