### ISSUE TITLE
Add a new ImageMenu API

### ISSUE THREAD

**Issue by zhuyaliang** [mate-desktop/mate-desktop#550]
```gtk_image_menu_item_new``` has been deprecated since version 3.10 and should not be used in newly-written code.We use a lot of ```gtk_image_menu_item``` in our code, which has resulted in a large number of compilation warnings. To eliminate compilation warnings, I plan to add a new API ```mate_image_menu_item```.
If there is no objection, I will start working immediately

**Comment by lukefromdc** [comment]
Go for it, being aware we probably won't ever go to GTK 4 for many reasons at this point. Taking
this in-house would mean we are no longer vulnerable to bitrot on this item though. Right now we
have GNOME responsible for maintaining widgets and functions they no longer use in-house,
which means those who write and maintain them have to deliberately test on code they use for
nothing else if they wish to prevent them from bitrotting.
