### ISSUE TITLE
New window opens behind maximized window

### ISSUE THREAD

**Issue by panmarco83** [mate-desktop/mate-desktop#552]
#### Expected behaviour
New windows should be shown in front of maximized window.

#### Actual behaviour
New window is behind maximized window

#### Steps to reproduce the behaviour
* Maximize a window
* open a new window or program

#### MATE general version
1.27.0

#### Package version
1.26.1-1

#### Linux Distribution
ARCH

#### Link to bugreport of your Distribution (requirement)
?

**Comment by lukefromdc** [comment]
This is a window manager issue, thus this needs to be moved to Marco
