### ISSUE TITLE
meson: libstartup-notification support does not actually build if selected

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-desktop#570]
#### Expected behaviour
On a meson build with these options
`meson setup build --prefix /usr -Dstartup-notification=true`
libstartup notification should be used. On opening mate-control-center and starting a capplet, the cursor should change
to the "cursor-busy" symbol (usually spinning) while the capplet opens (in Xorg only not in wayland).
This is the same behavior as with autotools. 
In autotools it is the default and in meson it is not and must be enabled with `-Dstartup-notification=true` 

#### Actual behaviour
Building with `meson setup build --prefix /usr -Dstartup-notification=true` will show in meson's (short) config summary will show startup notification support as an enabled user selected option, the package will build and install.
At runtime however it will be visible that libstartup-notification is not actually being used, as on opening a capplet from mate-control-center the cursor stays the normal arrow

#### Steps to reproduce the behaviour
Build mate-desktop using meson with
`Building with `meson setup build --prefix /usr -Dstartup-notification=true` `
Install the build, open mate-control-center, and open any capplet from it. The cursor does not change to the busy cursor

Now build with autotools and install, NOT disabling startup notification support, it is enabled by default if libstartup-notification and any necessary development package is installed. Again open mate-control-center, again start a capplet. Watch the cursor, now you see the momentary change to the busy cursor.

#### MATE general version
1.27

#### Package version
Duplicated on 1.27.1 as released and on current git master, no change in behavior so not caused by any recent commit

#### Linux Distribution
Debian Unstable

#### Link to bugreport of your Distribution (requirement)
None as this is a local build

**Comment by lukefromdc** [comment]
Note that confusion caused by this led to multiple Travis build failures while working on https://github.com/mate-desktop/mate-desktop/pull/566

**Comment by raveit65** [comment]
Enable_startup_notification should be true to be consistent with x11 behavior.

**Comment by lukefromdc** [comment]
in meson_options.txt we have
```

option('startup-notification',
  type: 'boolean',
  value: 'false',
  description: 'startup notification support'
)
```
which should default to true to match autotools behavior. Manually enabling it with `-Dstartup-notification=true` is what only claimed to work and did not actually work
