### ISSUE TITLE
Add a mate-portals.conf for xdg-desktop-portal

### ISSUE THREAD

**Issue by smcv** [mate-desktop/mate-desktop#574]
As a small and straightforward step towards mate-desktop/mate-desktop#504, it would be useful for some central component of MATE to install a `mate-portals.conf` for xdg-desktop-portal >= 1.17, indicating the MATE maintainers' recommended portal backend for use with MATE. If that recommendation is currently [x-d-p-gtk](https://github.com/flatpak/xdg-desktop-portal-gtk), then that would be as simple as this (untested, I don't normally run MATE):

```
# /usr/share/xdg-desktop-portal/mate-portals.conf
[preferred]
default=gtk;
```

[More information](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1050803)

If this file doesn't exist, x-d-p will fall back to the deprecated `UseIn` keys.

The GNOME equivalent of this is [in gnome-session](https://gitlab.gnome.org/GNOME/gnome-session/-/merge_requests/95). In MATE, I've guessed that mate-session-manager would similarly be the most appropriate home for this, as the component that sets `DesktopNames=MATE`; but any component that mate-session-manager depends on (like mate-desktop?) would also be fine.

Each x-d-p backend can implement any subset of the interfaces used by x-d-p: they are not necessarily required to implement the full set. It's entirely possible that the right thing to do for MATE would be to rely on xdp-gtk for the interfaces that are straightforward to implement in a mostly-desktop-independent way (like the file chooser), but then use a MATE-specific backend as requested in mate-desktop/mate-desktop#504 for other interfaces (like maybe screenshots). For example, GNOME uses xdp-gnome for most interfaces, but the backend for Secrets is in gnome-keyring, and the backend for Access is in gnome-shell, both of which were easier or more appropriate places to put that functionality.

In mate-desktop/mate-desktop#504, @raveit65 writes:
> Nope, xapps are cinamon only production. There xapps are only forks from origin MATE applications like Atril, eom, engrampa. In other words we don't need that.

x-d-p-xapp seems to think that it's targeting Cinnamon, MATE and XFCE, not just Cinnamon - it has `UseIn=X-Cinnamon;MATE;XFCE;`. This is one of the reasons why x-d-p added `portals.conf(5)` - so that it can be the desktop environment, not the portal implementation, that makes the choice of which portal implementation(s) each desktop should be using.

#### Steps to reproduce the behaviour

* Install xdg-desktop-portal 1.17.x (in, for example, Debian unstable or Ubuntu 23.10), or stable release 1.18.x (expected to be released later this month)
* Log in to a MATE session
* Use an application that uses portals, for example [libportal's demos](https://github.com/flatpak/libportal) or [ashpd's demo](https://flathub.org/en-GB/apps/com.belmoussaoui.ashpd.demo)

#### Expected behaviour

* Portals are chosen according to the desktop environment maintainers' choice, unless configured differently by the sysadmin or user

#### Actual behaviour

* xdg-desktop-portal logs deprecation warnings, and falls back to using portals that mention MATE in their `UseIn` key
* In practice, x-d-p-xapp will be used for several interfaces if installed, even if the MATE maintainers might prefer x-d-p-gtk

#### MATE general version

n/a, current version seems to be affected but I don't run MATE myself

#### Package version

n/a

#### Linux Distribution

any

#### Link to bugreport of your Distribution (requirement)

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1050803

**Comment by raveit65** [comment]
I will try to test this file. Can i add this line `org.freedesktop.impl.portal.Secret=gnome-keyring;` to the file because we are using gnome-keyring?
Or need this registrated at x-d-p?
How can i verify at command line that it works?

**Comment by raveit65** [comment]
Ok, i can reproduce/verify it with using libportaldemo

**Comment by smcv** [comment]
> How can i verify at command line that it works?

Not at a command-line, but the [libportal manual test programs](https://github.com/flatpak/libportal), the [ashpd demo](https://flathub.org/en-GB/apps/com.belmoussaoui.ashpd.demo) and [Door Knocker](https://flathub.org/apps/xyz.tytanium.DoorKnocker) are all useful for poking at portals interactively.

I don't think any of those interact with Secrets specifically, but according to codesearch.debian.net, libsecret seems to have some sort of support for contacting `org.freedesktop.portal.Secret` (which is the desktop-independent x-d-p frontend to any desktop environment's `org.freedesktop.impl.portal.Secret` backend).

> Can i add this line `org.freedesktop.impl.portal.Secret=gnome-keyring;` to the file because we are using gnome-keyring?

If MATE uses gnome-keyring like GNOME does, and it works normally in a MATE session (not broken by some missing GNOME dependency), then yes, it seems like you should be able to use `gnome-keyring` as your implementation of `org.freedesktop.impl.portal.Secret` like GNOME does.

**Comment by raveit65** [comment]
There is too much noise in other report for me.
My intention was to reproduce the issue with gimp in a linux version which is use (fedora 38), to find a clear reproducer for adding a mate-portals.conf. But the issue isn't reproducible in fedora or in debian (post from another active Mate developer).
Any way, i set up an fresh fedora 39 VM with [xdg-desktop-portal-1.17.0-3.fc39](https://koji.fedoraproject.org/koji/buildinfo?buildID=2279197) . I will start with that content.
```
[preferred]
default=gtk;
org.freedesktop.impl.portal.Secret=gnome-keyring;
```
Is there an documentation for what content i can add to this file?

**Comment by smcv** [comment]
> Is there a documentation for what content i can add to this file?

Yes, https://github.com/flatpak/xdg-desktop-portal/blob/main/doc/portals-conf.rst

**Comment by lukefromdc** [comment]
Also note that when GIMP 3.0 (development, GTK3) is running in wayland without an active portal, the color picker can only see colors within GIMP's window due to the (in the absence of a portal) general restriction on apps reading oneanother's windows

**Comment by raveit65** [comment]
Thanks, ok that will be a next step , but now i know how it works.
