### ISSUE TITLE
desktop size issue after exit from full screen apps

### ISSUE THREAD

**Issue by rox4d** [mate-desktop/mate-desktop#593]
#### Expected behaviour
usable desktop size should be exactly same as before starting full screen app
#### Actual behaviour

usable desktop size are equal mode selected by full screen app (rectangle in upper left corner of screen)

#### Steps to reproduce the behaviour

run app in full screen mode with video mode lower current desktop ( i was try Ion Fury game (native) and Valley Benchmark 1.0 (wine) ), exit from it.
#### MATE general version
1.26.2

**Comment by lukefromdc** [comment]
Does this also happen if you reduce screen resolution in xrandr, then restore the original resolution? This looks like a failure to listen for screen resolution changes

**Comment by rox4d** [comment]
No, xrandr doesn't trigger this, but changing mode via xrandr restored desktop size to normal (according mode).

**Comment by lukefromdc** [comment]
I was just unable to duplicate this is Scorched3d, OpenInvaders, or Penguin-command while running compiz using a smaller resolution for the game in fullscreen mode. Monitor resolution is 4K. Note that I am on 1.27 from git master though. I cannot test larger games I don't already have installed: not enough bandwidth for big downloads, and no proprietary game stuff at all. If this is generic to all

**Comment by lukefromdc** [comment]
> I was just unable to duplicate this is Scorched3d, OpenInvaders, or Penguin-command while running Compiz or Marco using a smaller resolution for the game in fullscreen mode. Monitor resolution is 4K. Note that I am on 1.27 from git master though. I cannot test larger games I don't already have installed: not enough bandwidth for big downloads, and no proprietary game stuff at all. If this is generic to all

**Comment by rox4d** [comment]
Do you have a single monitor setup? with dual monitors at least while running at primary monitor it work correctly.
p.s. It seems generic,  with scorched3d-44+dfsg-8+b2 it has a simalar behaviour.

**Comment by lukefromdc** [comment]
Test was on a single monitor. Right now I only set duals up for testing code related to that.

**Comment by rox4d** [comment]
are instructions for build from git exist?

**Comment by lukefromdc** [comment]
I would refer this to the rest of the team, as I do this from what's stored in my
head. The README files have some very general information in them.

**Comment by rox4d** [comment]
looks like it works in current git (1.27.3)
