### ISSUE TITLE
mate-screenshot: Current window captures have a line through title bar

### ISSUE THREAD

**Issue by negge** [mate-desktop/mate-desktop#594]
#### Expected behaviour

An exact copy of displayed window as a PNG

#### Actual behaviour

Title bar has a line through it (flawed capture)

#### Steps to reproduce the behaviour

Accessories | Take Screenshot | Grab the current window

#### MATE general version

MATE 1.26

#### Package version

mate-extra/mate-utils-1.26.0

#### Linux Distribution

gentoo

#### Link to bugreport of your Distribution (requirement)

https://bugs.gentoo.org/917395

#### Screenshot of issue

![Screenshot at 2023-11-15 16-39-58](https://github.com/mate-desktop/mate-desktop/assets/280940/83356efc-151f-4e08-8e09-e2c39ce66059)

#### Screenshot of [uncropped] expected output

![Screenshot at 2023-11-15 17-25-52-E](https://github.com/mate-desktop/mate-desktop/assets/280940/147cb2cd-e4d8-4635-97fb-b3dbff460e05)

**Comment by lukefromdc** [comment]
Assuming you are using marco as the WM as including the border does not work in compiz. Do you have compositing turned on? I suspect this may be fallout from earlier work to stop mate-screenshot from including the shadow area when compositing as big black bars all the way around

**Comment by negge** [comment]
I am using marco and I do not have compositing turned on. There is no shadow area around the windows (but I do remember this earlier problem when I tested that).

**Comment by negge** [comment]
> I suspect this may be fallout from earlier work to stop mate-screenshot from including the shadow area when compositing as big black bars all the way around

@lukefromdc  Do you have a link to these commits? I'd like to see if there is anything obviously wrong there.

**Comment by lukefromdc** [comment]
This issue should be moved to mate-utils, as that's the package containing mate-screenshot. 

I cannot find the old commits (without spending hours looking for them right now) if any that dealt with the black borders (might have been in marco not the screenshooter for all I know) but the invisible borders/shadow areas work in Marco was years ago. As of now, running marco with compositing ON and including window borders I get the correct behavior: the area around the window (shadow area) shows the desktop beneath it.

**Comment by lukefromdc** [comment]
Moved to https://github.com/mate-desktop/mate-utils/issues/360 so closing here. Link there allows comments here to be found
