### ISSUE TITLE
"Lock Icons Position" doesn't block "Organize Desktop by Name" function

### ISSUE THREAD

**Issue by rox4d** [mate-desktop/mate-desktop#595]
#### Expected behaviour
"Lock Icons Position" should prevent to change  icons positions  from selecting (mostly accidentally)  "Organize Desktop by Name" 

#### Actual behaviour
"Lock Icons Position" does`t prevent "Organize Desktop by Name" to change icons positions, against it prevent user to move icons

#### Steps to reproduce the behaviour
Arrange desktop icons as you like, press right mouse button at desktop, in menu select "Lock Icons Position" item, then again press right mouse button at desktop and select "Organize Desktop by Name"

#### MATE general version
1.27.3 and early

#### Package version
git build

#### Linux Distribution

Debian bullseye

**Comment by lukefromdc** [comment]
This means the code for "organize desktop by name" needs to check for icons being locked before executing

**Comment by rox4d** [comment]
or making menu item "Organize Desktop by Name" inactive while "Lock Icons Position" selected

**Comment by rox4d** [comment]
i.e. something like this:
~~~
diff -urN a/src/file-manager/fm-icon-view.c b/src/file-manager/fm-icon-view.c
--- a/src/file-manager/fm-icon-view.c	2023-11-25 18:43:04.081487612 +0300
+++ b/src/file-manager/fm-icon-view.c	2023-11-25 18:52:01.338670185 +0300
@@ -1674,11 +1674,16 @@
     FMIconView *icon_view;
     CajaFile *file;
     gboolean lock_icons_position;
+    GtkAction *action_other;
 
     icon_view = FM_ICON_VIEW (user_data);
 
     lock_icons_position = gtk_toggle_action_get_active (GTK_TOGGLE_ACTION (action));
 
+    action_other = gtk_action_group_get_action (icon_view->details->icon_action_group,
+                                                FM_ACTION_CLEAN_UP);
+    gtk_action_set_visible (action_other, !lock_icons_position);
+
     file = fm_directory_view_get_directory_as_file (FM_DIRECTORY_VIEW (icon_view));
     fm_icon_view_set_directory_lock_icons_position (icon_view,
             file,
~~~

**Comment by lukefromdc** [comment]
I can verify that the proposed fix works: if icon positions are locked, the "Organize Desktop by Name" menu item does not appear in the right click menu. Will submit as a PR

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/pull/1752 fixes this, worked in my test

**Comment by rox4d** [comment]
> https://github.com/mate-desktop/caja/pull/1752 fixes this

Thanks for your great work!

**Comment by lukefromdc** [comment]
It's actually your work, I just turned it into a PR so it could be tested and if no problems come up be merged into caja
