### ISSUE TITLE
Qt - PySide6 doesn't render the selected text in a combbox inside a groupbox, instead it's a blank box

### ISSUE THREAD

**Issue by lazyarse** [mate-desktop/mate-desktop#597]
#### Expected behaviour
For the combobox to show the available options (without being clicked)

#### Actual behaviour
The combobox shows a blank box and only clicking on it will show the text options. When a text option is clicked and selected, the combobox returns to its small size and again, no text is shown. The combobox does show the selected option whilst the window is being resized

#### Steps to reproduce the behaviour
Python 3.11

```python3
from PySide6.QtWidgets import QApplication, QFrame, QGroupBox, QComboBox, QWidget, QVBoxLayout
import sys

class MyWidget(QWidget):
    def __init__(self):
        super().__init__()

        groupbox = QGroupBox(self)
        groupbox_layout = QVBoxLayout(groupbox)
        
        combo = QComboBox(groupbox)
        combo.addItems(["Option 1", "Option 2", "Option 3"])
        groupbox_layout.addWidget(combo)

        layout = QVBoxLayout(self)
        layout.addWidget(groupbox)

app = QApplication(sys.argv)
window = MyWidget()
window.show()
sys.exit(app.exec())
```

#### MATE general version
1.26.2

#### Linux Distribution
Debian 12

#### Link to bugreport of your Distribution (requirement)
[1059530](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1059530)

**Comment by lukefromdc** [comment]
This doesn't look like it has anything to do with MATE itself. We maintain neither GTK nor QT, this will be either a toolset bug or an issue with Pyside6, which again is not one of our apps
