### ISSUE TITLE
Please don't forget a blog entry post for mate desktop 1.28.0

### ISSUE THREAD

**Issue by rubyFeedback** [mate-desktop/mate-desktop#599]
Hey guys,

Please don't forget a blog entry post for mate desktop 1.28.0. I notice that this
appears to be in-process, e. g. some components have been updated, probably more
will be updated in the coming hours or days (or weeks?).

Once done please don't forget someone to update the blog on the homepage.
Thank you.

**Comment by lukefromdc** [comment]
We will most certainly want to include mention of the new wayland session and much better wayland support.

**Comment by ander-san** [comment]
I understand, but could you guys at least post something like: "We're alive! wait for exciting news soon!" ???
Some people think the project was abandoned due to the lack of updates since 2021 (if any doubt, google it!), despite the github activity (most people are unware of it).

**Comment by mbkma** [comment]
Fixed by https://github.com/mate-desktop/mate-desktop.org/pull/734#issuecomment-2141426510
