### ISSUE TITLE
nm-applet exits when opening or closing vpn

### ISSUE THREAD

**Issue by PisikeSipelgas** [mate-desktop/mate-desktop#622]
#### Actual behaviour
When opening vpn through nm-applet from taskbar,  nm-applet exits. 

#### Steps to reproduce the behaviour
Configure a vpn (i have openvpn and wireguard). Open or close one of them and most of the times nm-applet exits.

#### MATE general version
Mate 1.26.2

#### Package version
network-manager-gnome   1.34.0+mint1+wilma

#### Linux Distribution
Linux Mint 22 (Wilma)

**Comment by lukefromdc** [comment]
MATE does not provde or maintain nm-applet. This is gnome-network-manager, still provided by gnome and maintained after all these years. Wr juat provide the status ixon or SNI support (it supports both) for it to render in, nothing mote.

**Comment by PisikeSipelgas** [comment]
Well then...
